<Project>

  <PropertyGroup Condition="'$(IsAotCompatible)' == '' and '$(OutputType)' == 'Library' and $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net11.0'))">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true'">
    <None Include="$(MSBuildThisFileDirectory)src/README.md" Pack="true" PackagePath="/" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)docs/assets/package-icon.png" Pack="true" PackagePath="icon.png" Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsPackable)' == 'true' and '$(IncludeBuildOutput)' != 'false'">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
  </ItemGroup>

</Project>
