<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="CsCheck" Version="4.9.1" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="ClangSharp" Version="21.1.8.4" />
  </ItemGroup>

</Project>
