<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../interop/Jade.Sdl/Jade.Sdl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(ArtifactsPath)/native/bin/$(NETCoreSdkPortableRuntimeIdentifier)/*" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

</Project>
