<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Jade/Jade.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../build/versions.json" Link="versions.json" CopyToOutputDirectory="PreserveNewest" Visible="false" />
    <None Include="../../native/*/buildTransitive/*.targets" Link="native/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

</Project>
