<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Jade.Interop\Jade.Interop.csproj" />
  </ItemGroup>

</Project>
