using System.Diagnostics;
using Jade.BindingGenerator.Projection;

namespace Jade.BindingGenerator.Emission;

/// <summary>Writes the idiomatic layer of an interop library above its raw layer (ADR 0029, ADR 0040).</summary>
/// <remarks>
/// New public types (mirrors, snapshots, extension slots) get a file of their own; what the
/// idiomatic layer adds to a handle or a value structure of the raw layer goes to a second partial
/// file, <c>{Type}.Idiomatic.g.cs</c>. The output depends only on the projected library, as the raw
/// layer's does (ADR 0007).
/// </remarks>
internal static class IdiomaticLayerEmitter
{
    /// <summary>The suffix of the files that add members to a type of the raw layer.</summary>
    private const string PartialSuffix = ".Idiomatic";

    /// <summary>The interface of input extensions, implemented by the generated types only (ADR 0029).</summary>
    private const string InputInterface = "global::Jade.Wgpu.IChainedExtension";

    /// <summary>The interface of output extensions, implemented by the generated types only (ADR 0040).</summary>
    private const string OutputInterface = "global::Jade.Wgpu.IChainedOutputExtension";

    /// <summary>The attribute of the trampolines that the native library calls.</summary>
    private const string UnmanagedCallersOnly = "[global::System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]";

    /// <summary>The statement that creates the arena of a call, over stack memory (ADR 0029).</summary>
    private const string ArenaDeclaration = "var arena = new Arena(stackalloc byte[Arena.StackSize]);";

    /// <summary>The prefix of the raw functions.</summary>
    private const string NativeMethods = "Raw.NativeMethods";

    /// <summary>Writes the files of a library's idiomatic layer.</summary>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <returns>The files, ordered by name.</returns>
    public static IReadOnlyList<GeneratedFile> Emit(IdiomaticLibrary library)
    {
        IEnumerable<GeneratedFile> files =
        [
            .. library.Handles.Select(handle => new GeneratedFile($"{handle.Name}{PartialSuffix}.g.cs", EmitFile(library, writer => EmitHandle(writer, library, handle)))),
            .. library.Structures.Select(structure => new GeneratedFile($"{structure.Name}.g.cs", EmitFile(library, writer => EmitStructure(writer, library, structure)))),
            .. library.ValueStructures.Select(structure => new GeneratedFile($"{structure.Name}{PartialSuffix}.g.cs", EmitFile(library, writer => EmitValueStructure(writer, library, structure)))),
            .. library.Slots.Select(slots => new GeneratedFile($"{slots.Name}.g.cs", EmitFile(library, writer => EmitSlots(writer, library, slots)))),
        ];

        return [.. files.OrderBy(static file => file.Name, StringComparer.Ordinal)];
    }

    /// <summary>Writes a file: its header, its namespace and one type.</summary>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="emitType">Writes the type.</param>
    /// <returns>The source text.</returns>
    private static string EmitFile(IdiomaticLibrary library, Action<CSharpWriter> emitType)
    {
        var writer = new CSharpWriter();

        writer.Line("// <auto-generated/>");
        writer.Line($"// Generated by scripts/binding-generator.cs from interop/{library.Namespace}/bindings.json. Do not edit:");
        writer.Line("// change the generator or its configuration and regenerate.");
        writer.Line();
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {library.Namespace};");
        writer.Line();
        emitType(writer);

        return writer.ToString();
    }

    /// <summary>Writes what the idiomatic layer adds to a handle: its constants, methods and properties, and <see cref="IDisposable"/>.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="handle">The handle.</param>
    private static void EmitHandle(CSharpWriter writer, IdiomaticLibrary library, IdiomaticHandle handle)
    {
        var isDisposable = handle.Methods.Any(static method => method.Kind == IdiomaticMethodKind.Release);

        writer.Line($"public readonly unsafe partial struct {handle.Name}{(isDisposable ? " : global::System.IDisposable" : string.Empty)}");
        writer.OpenBlock();

        var first = EmitConstants(writer, handle.Constants);

        foreach (var method in handle.Methods)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            EmitMethod(writer, library, handle, method);
        }

        writer.CloseBlock();
    }

    /// <summary>Writes the constants placed on a type.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="constants">The constants.</param>
    /// <returns><see langword="true"/> when nothing was written, so that the next member needs no blank line.</returns>
    private static bool EmitConstants(CSharpWriter writer, IReadOnlyList<IdiomaticConstant> constants)
    {
        var first = true;

        foreach (var constant in constants)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            writer.Line($"/// <summary>Maps <c>{constant.CName}</c>.</summary>");
            writer.Line(constant.IsConst
                ? $"public const {constant.Type} {constant.Name} = {constant.Value};"
                : $"public static {constant.Type} {constant.Name} => {constant.Value};");
        }

        return first;
    }

    /// <summary>Writes one member of a handle and the overloads it needs.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="handle">The handle.</param>
    /// <param name="method">The member.</param>
    private static void EmitMethod(CSharpWriter writer, IdiomaticLibrary library, IdiomaticHandle handle, IdiomaticMethod method)
    {
        switch (method.Kind)
        {
            case IdiomaticMethodKind.AddRef:
                writer.Line($"/// <summary>Adds a reference to the object: calls <c>{method.Function.CName}</c>. Nothing happens for a handle without object.</summary>");
                EmitGuardedCall(writer, method);
                break;

            case IdiomaticMethodKind.Release:
                writer.Line($"/// <summary>Releases a reference to the object: calls <c>{method.Function.CName}</c>. Nothing happens for a handle without object.</summary>");
                EmitGuardedCall(writer, method);
                writer.Line();
                writer.Line("/// <summary>Releases the reference this handle holds, as <see cref=\"Release\"/> does.</summary>");
                writer.Line("public void Dispose()");
                writer.OpenBlock();
                writer.Line("Release();");
                writer.CloseBlock();
                break;

            case IdiomaticMethodKind.Property:
                writer.Line($"/// <summary>Gets the result of <c>{method.Function.CName}</c>.</summary>");
                EmitAvailability(writer, method.Availability, handle.Availability);
                writer.Line($"public {method.ReturnType} {method.Name} => {NativeMethods}.{method.RawName}(this);");
                break;

            case IdiomaticMethodKind.Method:
            case IdiomaticMethodKind.Static:
                EmitCallable(writer, library, handle, method);
                break;

            default:
                throw new UnreachableException($"Unknown method kind {method.Kind}.");
        }
    }

    /// <summary>Writes <c>AddRef</c> or <c>Release</c>, which do nothing for a handle without object.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="method">The member.</param>
    private static void EmitGuardedCall(CSharpWriter writer, IdiomaticMethod method)
    {
        writer.Line($"public void {method.Name}()");
        writer.OpenBlock();
        writer.Line("if (Handle != 0)");
        writer.OpenBlock();
        writer.Line($"{NativeMethods}.{method.RawName}(this);");
        writer.CloseBlock();
        writer.CloseBlock();
    }

    /// <summary>Writes a method or a static method, with its overloads, its core and its trampoline.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="handle">The handle.</param>
    /// <param name="method">The method.</param>
    private static void EmitCallable(CSharpWriter writer, IdiomaticLibrary library, IdiomaticHandle handle, IdiomaticMethod method)
    {
        var shape = MethodShape.Create(method, library.ChainNext);
        var overloads = shape.GetOverloads();

        if (overloads.Count == 1)
        {
            EmitOverloadHeader(writer, handle, method, shape, overloads[0]);
            writer.OpenBlock();
            EmitArenaScope(writer, shape.CoreNeedsArena, () => EmitBody(writer, method, shape, isCore: false));
            writer.CloseBlock();
        }
        else
        {
            foreach (var overload in overloads)
            {
                if (overload != overloads[0])
                {
                    writer.Line();
                }

                EmitOverloadHeader(writer, handle, method, shape, overload);
                writer.OpenBlock();
                EmitOverloadBody(writer, method, shape, overload);
                writer.CloseBlock();
            }

            writer.Line();
            EmitCore(writer, method, shape);
        }

        if (method.Async is { } async)
        {
            writer.Line();
            EmitTrampoline(writer, method, async);
        }
    }

    /// <summary>Writes the documentation, attributes and signature of a public overload.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="handle">The handle.</param>
    /// <param name="method">The method.</param>
    /// <param name="shape">The shape of the method.</param>
    /// <param name="overload">The overload.</param>
    private static void EmitOverloadHeader(CSharpWriter writer, IdiomaticHandle handle, IdiomaticMethod method, MethodShape shape, MethodOverload overload)
    {
        var parameters = shape.GetOverloadParameters(overload);
        var typeParameters = shape.GetTypeParameters(overload);

        writer.Line(method.Async is null
            ? $"/// <summary>Calls <c>{method.Function.CName}</c>.</summary>"
            : $"/// <summary>Calls <c>{method.Function.CName}</c>. The task completes when <c>ProcessEvents</c> of the instance delivers the callback.</summary>");

        foreach (var (typeParameter, _) in typeParameters)
        {
            writer.Line($"/// <typeparam name=\"{typeParameter}\">{(typeParameter == "TData" ? "The type of the elements of the data." : "The type of the extension.")}</typeparam>");
        }

        foreach (var parameter in parameters)
        {
            writer.Line($"/// <param name=\"{parameter.Name}\">{parameter.Documentation}</param>");
        }

        switch (method.ReturnKind)
        {
            case IdiomaticReturnKind.Value:
                writer.Line($"/// <returns>The result of <c>{method.Function.CName}</c>.</returns>");
                break;

            case IdiomaticReturnKind.Output:
                writer.Line("/// <returns>The structure the function fills in.</returns>");
                break;

            case IdiomaticReturnKind.Task:
                writer.Line(method.Async!.ResultType is null
                    ? "/// <returns>A task that completes when the callback reports success.</returns>"
                    : "/// <returns>A task that completes with the result the callback reports.</returns>");
                break;

            case IdiomaticReturnKind.Void:
            case IdiomaticReturnKind.Status:
            default:
                break;
        }

        if (method.ChecksStatus)
        {
            writer.Line("/// <exception cref=\"WgpuException\">The function reports an error status.</exception>");
        }

        if (overload.Text == TextForm.Utf8)
        {
            writer.Line("[global::System.Runtime.CompilerServices.OverloadResolutionPriority(1)]");
        }

        EmitAvailability(writer, method.Availability, handle.Availability);
        writer.Line($"public {(method.Kind == IdiomaticMethodKind.Static ? "static " : string.Empty)}{method.ReturnType} {method.Name}{FormatTypeParameters(typeParameters)}({string.Join(", ", parameters.Select(static parameter => parameter.Declaration))})");
        EmitConstraints(writer, typeParameters);
    }

    /// <summary>Writes the body of a public overload that delegates to the core.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="method">The method.</param>
    /// <param name="shape">The shape of the method.</param>
    /// <param name="overload">The overload.</param>
    private static void EmitOverloadBody(CSharpWriter writer, IdiomaticMethod method, MethodShape shape, MethodOverload overload)
    {
        var needsArena = shape.CoreNeedsArena || overload.InputExtensions > 0 || overload.OutputExtensions > 0;
        var returns = method.ReturnType != "void";

        EmitArenaScope(writer, needsArena, () =>
        {
            if (overload.InputExtensions == 1)
            {
                writer.Line("var chain = TExtension.Lower(in extension, ref arena);");
            }
            else if (overload.InputExtensions == 2)
            {
                writer.Line("var chain = TExtension1.Lower(in extension1, ref arena);");
                writer.Line("var chain2 = TExtension2.Lower(in extension2, ref arena);");
                writer.Line($"chain->{shape.ChainNext} = chain2;");
            }

            if (overload.OutputExtensions == 1)
            {
                writer.Line("var outputChain = TExtension.Allocate(ref arena);");
            }
            else if (overload.OutputExtensions == 2)
            {
                writer.Line("var outputChain = TExtension1.Allocate(ref arena);");
                writer.Line("var outputChain2 = TExtension2.Allocate(ref arena);");
                writer.Line($"outputChain->{shape.ChainNext} = outputChain2;");
            }

            var call = $"{method.Name}Core{(shape.HasData ? "<TData>" : string.Empty)}({string.Join(", ", shape.GetCoreArguments(overload))})";

            if (overload.OutputExtensions == 0)
            {
                writer.Line(returns ? $"return {call};" : $"{call};");
                return;
            }

            writer.Line($"var result = {call};");

            if (overload.OutputExtensions == 1)
            {
                writer.Line("extension = TExtension.Raise(outputChain);");
            }
            else
            {
                writer.Line("extension1 = TExtension1.Raise(outputChain);");
                writer.Line("extension2 = TExtension2.Raise(outputChain2);");
            }

            writer.Line("return result;");
        });
    }

    /// <summary>Writes the private core that every overload of a method calls.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="method">The method.</param>
    /// <param name="shape">The shape of the method.</param>
    private static void EmitCore(CSharpWriter writer, IdiomaticMethod method, MethodShape shape)
    {
        writer.Line($"/// <summary>Calls <c>{method.Function.CName}</c> for every overload of <c>{method.Name}</c>.</summary>");
        writer.Line($"private {(method.Kind == IdiomaticMethodKind.Static ? "static " : string.Empty)}{method.ReturnType} {method.Name}Core{(shape.HasData ? "<TData>" : string.Empty)}({string.Join(", ", shape.GetCoreParameters())})");

        if (shape.HasData)
        {
            writer.Line("    where TData : unmanaged");
        }

        writer.OpenBlock();
        EmitBody(writer, method, shape, isCore: true);
        writer.CloseBlock();
    }

    /// <summary>Writes the code of a call: pinning, lowering, the native call and the conversion of its result.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="method">The method.</param>
    /// <param name="shape">The shape of the method.</param>
    /// <param name="isCore">Whether the code is the core's, whose optional parameters come with a presence flag and whose chains are parameters.</param>
    private static void EmitBody(CSharpWriter writer, IdiomaticMethod method, MethodShape shape, bool isCore)
    {
        var async = method.Async;
        var completionType = async is null ? null : async.ResultType is { } resultType ? $"global::System.Threading.Tasks.TaskCompletionSource<{resultType}>" : "global::System.Threading.Tasks.TaskCompletionSource";

        if (completionType is not null)
        {
            writer.Line($"var completion = new {completionType}(global::System.Threading.Tasks.TaskCreationOptions.RunContinuationsAsynchronously);");
            writer.Line($"var completionHandle = new global::System.Runtime.InteropServices.GCHandle<{completionType}>(completion);");
            writer.Line();
            writer.Line("try");
            writer.OpenBlock();
        }

        var fixedLines = shape.GetFixedStatements().ToList();

        foreach (var line in fixedLines)
        {
            writer.Line(line);
        }

        if (fixedLines.Count > 0)
        {
            writer.OpenBlock();
        }

        foreach (var parameter in method.Parameters)
        {
            var optional = isCore && parameter.IsOptional;

            switch (parameter.Kind)
            {
                case IdiomaticParameterKind.Descriptor:
                    writer.Line($"{parameter.RawStructure} {parameter.Name}Raw;");

                    if (optional)
                    {
                        writer.Line();
                        writer.Line($"if ({MethodShape.GetPresenceName(parameter)})");
                        writer.OpenBlock();
                    }

                    writer.Line($"{parameter.Name}.Lower({string.Join(", ", [$"&{parameter.Name}Raw", "ref arena", .. MethodShape.GetPinnedMembers(parameter).Select(member => $"{parameter.Name}{member.Name}Pointer")])});");

                    if (isCore && parameter.HasExtensions)
                    {
                        writer.Line($"{parameter.Name}Raw.{parameter.NextInChainField} = chain;");
                    }

                    if (optional)
                    {
                        writer.CloseBlock();
                    }

                    writer.Line();
                    break;

                case IdiomaticParameterKind.InValue when isCore && parameter.HasExtensions:
                    writer.Line($"var {parameter.Name}Copy = {parameter.Name};");
                    writer.Line($"{parameter.Name}Copy.{parameter.NextInChainField} = chain;");
                    writer.Line();
                    break;

                case IdiomaticParameterKind.Output:
                    writer.Line($"var {parameter.Name} = new {parameter.RawStructure}();");

                    if (isCore && parameter.HasExtensions)
                    {
                        writer.Line($"{parameter.Name}.{parameter.NextInChainField} = outputChain;");
                    }

                    writer.Line();
                    break;

                case IdiomaticParameterKind.Callback:
                    EmitCallbackInfo(writer, async!, completionType!);
                    break;

                case IdiomaticParameterKind.Value:
                case IdiomaticParameterKind.Boolean:
                case IdiomaticParameterKind.Pointer:
                case IdiomaticParameterKind.Text:
                case IdiomaticParameterKind.InValue:
                case IdiomaticParameterKind.Span:
                case IdiomaticParameterKind.MutableSpan:
                case IdiomaticParameterKind.Data:
                case IdiomaticParameterKind.MutableData:
                case IdiomaticParameterKind.Count:
                default:
                    break;
            }
        }

        var call = $"{NativeMethods}.{method.RawName}({string.Join(", ", shape.GetNativeArguments(isCore))})";
        var output = method.Parameters.FirstOrDefault(static parameter => parameter.Kind == IdiomaticParameterKind.Output);
        var statusCheck = $"WgpuException.ThrowIfFailed(status, \"{method.Function.CName}\");";

        switch (method.ReturnKind)
        {
            case IdiomaticReturnKind.Void:
                writer.Line($"{call};");
                break;

            case IdiomaticReturnKind.Value:
                writer.Line($"return {call};");
                break;

            case IdiomaticReturnKind.Status:
                writer.Line($"var status = {call};");
                writer.Line();
                writer.Line(statusCheck);
                break;

            case IdiomaticReturnKind.Task:
                writer.Line($"_ = {call};");
                break;

            case IdiomaticReturnKind.Output when output!.Snapshot is { } snapshot:
                writer.Line(method.ChecksStatus ? $"var status = {call};" : $"{call};");
                writer.Line();

                if (snapshot.FreeMembers is { } freeMembers)
                {
                    writer.Line("try");
                    writer.OpenBlock();
                }

                if (method.ChecksStatus)
                {
                    writer.Line(statusCheck);
                    writer.Line();
                }

                writer.Line($"return new {snapshot.Name}(in {output.Name});");

                if (snapshot.FreeMembers is { } free)
                {
                    writer.CloseBlock();
                    writer.Line("finally");
                    writer.OpenBlock();
                    writer.Line($"{NativeMethods}.{free}({output.Name});");
                    writer.CloseBlock();
                }

                break;

            case IdiomaticReturnKind.Output:
                writer.Line(method.ChecksStatus ? $"var status = {call};" : $"{call};");
                writer.Line();

                if (method.ChecksStatus)
                {
                    writer.Line(statusCheck);
                }

                if (isCore && output.HasExtensions)
                {
                    // The chain lives in the call's arena, which is gone once the method returns.
                    writer.Line($"{output.Name}.{output.NextInChainField} = null;");
                }

                writer.Line($"return {output.Name};");
                break;

            default:
                throw new UnreachableException($"Unknown return kind {method.ReturnKind}.");
        }

        if (fixedLines.Count > 0)
        {
            writer.CloseBlock();
        }

        if (completionType is not null)
        {
            writer.CloseBlock();
            writer.Line("catch");
            writer.OpenBlock();
            writer.Line("completionHandle.Dispose();");
            writer.Line("throw;");
            writer.CloseBlock();
            writer.Line();
            writer.Line("return completion.Task;");
        }
    }

    /// <summary>Writes the callback info of an asynchronous call, whose userdata holds the task's completion.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="async">How the callback completes the task.</param>
    /// <param name="completionType">The C# type of the completion.</param>
    private static void EmitCallbackInfo(CSharpWriter writer, IdiomaticAsync async, string completionType)
    {
        writer.Line($"var callbackInfo = new {async.CallbackInfoType}");
        writer.OpenBlock();

        if (async.ModeField is { } modeField)
        {
            writer.Line($"{modeField} = {async.ModeValue},");
        }

        writer.Line($"{async.CallbackField} = &{async.Trampoline},");
        writer.Line($"{async.UserdataField} = (void*)global::System.Runtime.InteropServices.GCHandle<{completionType}>.ToIntPtr(completionHandle),");
        writer.CloseBlock(";");
        writer.Line();
    }

    /// <summary>Writes the trampoline that the native library calls back, which completes the task.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="method">The method.</param>
    /// <param name="async">How the callback completes the task.</param>
    private static void EmitTrampoline(CSharpWriter writer, IdiomaticMethod method, IdiomaticAsync async)
    {
        var completionType = async.ResultType is { } resultType ? $"global::System.Threading.Tasks.TaskCompletionSource<{resultType}>" : "global::System.Threading.Tasks.TaskCompletionSource";
        var status = async.TrampolineParameters[0].Name;
        var success = $"{status} == {async.SuccessValue}";
        var result = async.ResultParameter switch
        {
            null => string.Empty,
            { } name when async.ResultIsSnapshot => $"new {async.ResultType}(in *{name})",
            { } name => name,
        };

        if (async.ResultIsSnapshot)
        {
            success += $" && {async.ResultParameter} != null";
        }

        writer.Line($"/// <summary>Completes the task of <c>{method.Function.CName}</c> when the library calls back; it never throws, since it runs inside a native call.</summary>");
        writer.Line(UnmanagedCallersOnly);
        writer.Line($"private static void {async.Trampoline}({string.Join(", ", async.TrampolineParameters.Select(static parameter => $"{parameter.Type} {parameter.Name}"))})");
        writer.OpenBlock();
        writer.Line($"var completionHandle = global::System.Runtime.InteropServices.GCHandle<{completionType}>.FromIntPtr((nint){async.UserdataParameter});");
        writer.Line("var completion = completionHandle.Target;");
        writer.Line();
        writer.Line("completionHandle.Dispose();");
        writer.Line();
        writer.Line($"if ({success})");
        writer.OpenBlock();
        writer.Line($"_ = completion.TrySetResult({result});");
        writer.CloseBlock();
        writer.Line("else");
        writer.OpenBlock();
        writer.Line(async.MessageParameter is { } message
            ? $"_ = completion.TrySetException(WgpuException.FromCallback({status}, \"{method.Function.CName}\", {message}));"
            : $"_ = completion.TrySetException(WgpuException.FromCallback({status}, \"{method.Function.CName}\"));");
        writer.CloseBlock();
        writer.CloseBlock();
    }

    /// <summary>Writes code inside the arena of a call when it needs one.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="needsArena">Whether the code lowers something into the arena.</param>
    /// <param name="emit">Writes the code.</param>
    private static void EmitArenaScope(CSharpWriter writer, bool needsArena, Action emit)
    {
        if (!needsArena)
        {
            emit();
            return;
        }

        writer.Line(ArenaDeclaration);
        writer.Line();
        writer.Line("try");
        writer.OpenBlock();
        emit();
        writer.CloseBlock();
        writer.Line("finally");
        writer.OpenBlock();
        writer.Line("arena.Dispose();");
        writer.CloseBlock();
    }

    /// <summary>Formats the type parameters of a method.</summary>
    /// <param name="typeParameters">The type parameters and their constraints.</param>
    /// <returns><c>&lt;T1, T2&gt;</c>, or nothing.</returns>
    private static string FormatTypeParameters(IReadOnlyList<(string Name, string Constraint)> typeParameters)
    {
        return typeParameters.Count == 0 ? string.Empty : $"<{string.Join(", ", typeParameters.Select(static parameter => parameter.Name))}>";
    }

    /// <summary>Writes the constraints of the type parameters of a method.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="typeParameters">The type parameters and their constraints.</param>
    private static void EmitConstraints(CSharpWriter writer, IReadOnlyList<(string Name, string Constraint)> typeParameters)
    {
        foreach (var (name, constraint) in typeParameters)
        {
            writer.Line($"    where {name} : {constraint}");
        }
    }

    /// <summary>Writes the platform attributes of a member available on fewer platforms than its type.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="availability">The platforms of the member.</param>
    /// <param name="typeAvailability">The platforms of its type.</param>
    private static void EmitAvailability(CSharpWriter writer, Targets.Platforms availability, Targets.Platforms typeAvailability)
    {
        if (availability != typeAvailability)
        {
            RawLayerEmitter.EmitPlatformAttributes(writer, availability);
        }
    }

    /// <summary>Writes a mirror, an element mirror or a snapshot.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="structure">The structure.</param>
    private static void EmitStructure(CSharpWriter writer, IdiomaticLibrary library, IdiomaticStructure structure)
    {
        switch (structure.Role)
        {
            case IdiomaticRole.Mirror:
            case IdiomaticRole.ElementMirror:
                MirrorEmitter.Emit(writer, library, structure);
                break;

            case IdiomaticRole.Snapshot:
                MirrorEmitter.EmitSnapshot(writer, library, structure);
                break;

            case IdiomaticRole.Unused:
            case IdiomaticRole.Value:
            case IdiomaticRole.StringView:
            case IdiomaticRole.ChainHeader:
            case IdiomaticRole.CallbackInfo:
            case IdiomaticRole.Skipped:
            default:
                throw new UnreachableException($"'{structure.Name}' is a {structure.Role} structure, which has no idiomatic type.");
        }
    }

    /// <summary>Writes what the idiomatic layer adds to a value structure: its constants and extension interfaces.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="structure">The value structure.</param>
    private static void EmitValueStructure(CSharpWriter writer, IdiomaticLibrary library, IdiomaticValueStructure structure)
    {
        var interfaces = structure.InputRoots.Select(root => $"{InputInterface}<{structure.Name}, {root}>")
            .Concat(structure.OutputRoots.Select(root => $"{OutputInterface}<{structure.Name}, {root}>"))
            .ToList();

        writer.Line($"public unsafe partial struct {structure.Name}{(interfaces.Count > 0 ? " : " + string.Join(", ", interfaces) : string.Empty)}");
        writer.OpenBlock();

        var first = EmitConstants(writer, structure.Constants);
        var chain = structure.ChainField;

        foreach (var root in structure.InputRoots)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            writer.Line("/// <inheritdoc/>");
            writer.Line($"static Raw.ChainedStruct* {InputInterface}<{structure.Name}, {root}>.Lower(scoped in {structure.Name} extension, scoped ref Arena arena)");
            writer.OpenBlock();
            writer.Line("var target = arena.Copy(in extension);");
            writer.Line();
            writer.Line($"target->{chain}.{library.ChainNext} = null;");
            writer.Line($"target->{chain}.{library.ChainType} = {structure.StructureType};");
            writer.Line();
            writer.Line($"return &target->{chain};");
            writer.CloseBlock();
        }

        foreach (var root in structure.OutputRoots)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            writer.Line("/// <inheritdoc/>");
            writer.Line($"static Raw.ChainedStruct* {OutputInterface}<{structure.Name}, {root}>.Allocate(scoped ref Arena arena)");
            writer.OpenBlock();
            writer.Line($"var target = arena.Allocate<{structure.Name}>();");
            writer.Line();
            writer.Line($"*target = new {structure.Name}();");
            writer.Line($"target->{chain}.{library.ChainNext} = null;");
            writer.Line($"target->{chain}.{library.ChainType} = {structure.StructureType};");
            writer.Line();
            writer.Line($"return &target->{chain};");
            writer.CloseBlock();
            writer.Line();
            writer.Line("/// <inheritdoc/>");
            writer.Line($"static {structure.Name} {OutputInterface}<{structure.Name}, {root}>.Raise(Raw.ChainedStruct* chain)");
            writer.OpenBlock();
            writer.Line($"var value = *({structure.Name}*)chain;");
            writer.Line();
            writer.Line($"value.{chain}.{library.ChainNext} = null;");
            writer.Line();
            writer.Line("return value;");
            writer.CloseBlock();
        }

        writer.CloseBlock();
    }

    /// <summary>Writes the slots of the extensions of a nested chain root.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected idiomatic layer.</param>
    /// <param name="slots">The slots.</param>
    private static void EmitSlots(CSharpWriter writer, IdiomaticLibrary library, IdiomaticSlots slots)
    {
        writer.Line($"/// <summary>The extensions chained to a <see cref=\"{slots.RootName}\"/> that a descriptor holds: each field that has a value is chained.</summary>");
        writer.Line(RawLayerEmitter.GeneratedCodeAttribute);
        RawLayerEmitter.EmitPlatformAttributes(writer, slots.Availability);
        writer.Line($"public unsafe partial struct {slots.Name}");
        writer.OpenBlock();

        foreach (var slot in slots.Extensions)
        {
            writer.Line($"/// <summary>Chains a <see cref=\"Jade.Wgpu.{slot.Name}\"/> when it has a value.</summary>");
            EmitAvailability(writer, slot.Availability, slots.Availability);
            writer.Line($"public {slot.Name}? {slot.Name};");
            writer.Line();
        }

        writer.Line("/// <summary>Copies the extensions that have a value into the arena and links them.</summary>");
        writer.Line("/// <param name=\"arena\">The memory of the call.</param>");
        writer.Line("/// <returns>The first extension, or <see langword=\"null\"/> when no field has a value.</returns>");
        writer.Line("internal readonly Raw.ChainedStruct* Lower(scoped ref Arena arena)");
        writer.OpenBlock();
        writer.Line("Raw.ChainedStruct* first = null;");

        foreach (var slot in slots.Extensions)
        {
            writer.Line();
            writer.Line($"if ({slot.Name}.HasValue)");
            writer.OpenBlock();
            writer.Line($"var extension = arena.Copy({slot.Name}.GetValueOrDefault());");
            writer.Line();
            writer.Line($"extension->{slot.ChainField}.{library.ChainNext} = first;");
            writer.Line($"extension->{slot.ChainField}.{library.ChainType} = {slot.StructureType};");
            writer.Line($"first = &extension->{slot.ChainField};");
            writer.CloseBlock();
        }

        writer.Line();
        writer.Line("return first;");
        writer.CloseBlock();
        writer.CloseBlock();
    }
}
