using Jade.BindingGenerator.Projection;
using Jade.BindingGenerator.Targets;

namespace Jade.BindingGenerator.Emission;

/// <summary>
/// Writes the layout tests of an interop library: a C source that reports the layouts the C
/// compiler gives its structures, and a C# test class that compares them with the C# layouts (ADR 0036).
/// </summary>
/// <remarks>
/// Both sides list the same entries under the same names: a record under its C name, with its size
/// and alignment, and each member as <c>{record}.{member}</c>, with its size and offset from the
/// start of the record; an array member adds its first element, <c>{record}.{member}[0]</c>. The
/// alignment of an anonymous record is reported as 0 on both sides: C11 has no way to name its
/// type, and the offsets and sizes of the records that hold it already depend on it.
/// </remarks>
internal static class LayoutTestEmitter
{
    /// <summary>The name of the generated C# file in the test project's <c>Generated/</c> directory.</summary>
    public const string TestFileName = "LayoutTests.g.cs";

    /// <summary>The header of the C side that declares the entry type and the macros, next to the generated sources.</summary>
    private const string NativeHeader = "jade_layout.h";

    /// <summary>The C macro that each platform family defines in <see cref="NativeHeader"/>, and the C# check of the same platform.</summary>
    private static readonly (Platforms Platform, string Macro, string Check)[] _platforms =
    [
        (Platforms.Windows, "JADE_LAYOUT_WINDOWS", "IsWindows"),
        (Platforms.Linux, "JADE_LAYOUT_LINUX", "IsLinux"),
        (Platforms.MacOS, "JADE_LAYOUT_MACOS", "IsMacOS"),
        (Platforms.IOS, "JADE_LAYOUT_IOS", "IsIOS"),
        (Platforms.Android, "JADE_LAYOUT_ANDROID", "IsAndroid"),
        (Platforms.Browser, "JADE_LAYOUT_BROWSER", "IsBrowser"),
    ];

    /// <summary>Writes the C source of a library's layout library.</summary>
    /// <param name="layouts">The layout tests.</param>
    /// <param name="directory">The directory of the source, relative to the repository root with <c>/</c> separators, which the includes of repository files are relative to.</param>
    /// <returns>The source text.</returns>
    /// <remarks>
    /// The source defines and includes what the generator parsed, in the same order, so that the
    /// compiler sees the declarations the bindings were generated from; only the include
    /// directories come from the build definition. Each record is guarded by the platforms it is
    /// available on, as the C# side is.
    /// </remarks>
    public static string EmitNativeSource(ProjectedLayouts layouts, string directory)
    {
        var writer = new CSharpWriter();
        var headers = layouts.Headers;

        writer.Line("/*");
        writer.Line(" * <auto-generated/>");
        writer.Line($" * Generated by scripts/binding-generator.cs from interop/{layouts.Namespace}/bindings.json. Do not edit:");
        writer.Line(" * change the generator or its configuration and regenerate.");
        writer.Line(" *");
        writer.Line($" * The layouts the C compiler gives the structures of {layouts.Namespace}, which");
        writer.Line($" * tests/{layouts.Namespace}.Tests compares with the C# layouts (docs/adr/0036).");
        writer.Line(" */");

        if (headers.Defines.Count > 0)
        {
            writer.Line();

            foreach (var define in headers.Defines)
            {
                writer.Line(define.Split('=', 2) is [var name, var value] ? $"#define {name} {value}" : $"#define {define}");
            }
        }

        writer.Line();

        foreach (var file in headers.ForcedIncludes)
        {
            writer.Line($"#include \"{GetRelativePath(directory, file)}\"");
        }

        foreach (var header in headers.Headers)
        {
            writer.Line($"#include <{header}>");
        }

        foreach (var shim in headers.Shims)
        {
            writer.Line($"#include \"{GetRelativePath(directory, shim)}\"");
        }

        writer.Line();
        writer.Line($"#include \"{NativeHeader}\"");
        writer.Line();
        writer.Line("static const jade_layout_entry entries[] = {");

        foreach (var record in layouts.Records)
        {
            var condition = GetNativeCondition(record.Availability);

            if (condition is not null)
            {
                writer.Line($"#if {condition}");
            }

            EmitNativeEntries(writer, record);

            if (condition is not null)
            {
                writer.Line("#endif");
            }
        }

        writer.Line("    JADE_LAYOUT_END,");
        writer.Line("};");
        writer.Line();
        writer.Line($"JADE_LAYOUT_API const jade_layout_entry* {layouts.NativeName}(void)");
        writer.OpenBlock();
        writer.Line("return entries;");
        writer.CloseBlock();

        return writer.ToString();
    }

    /// <summary>Writes the C# test class that compares the layouts.</summary>
    /// <param name="layouts">The layout tests.</param>
    /// <returns>The file, named <see cref="TestFileName"/>.</returns>
    public static GeneratedFile EmitTests(ProjectedLayouts layouts)
    {
        var writer = new CSharpWriter();

        writer.Line("// <auto-generated/>");
        writer.Line($"// Generated by scripts/binding-generator.cs from interop/{layouts.Namespace}/bindings.json. Do not edit:");
        writer.Line("// change the generator or its configuration and regenerate.");
        writer.Line();
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {layouts.Namespace}.Tests;");
        writer.Line();
        writer.Line("/// <summary>");
        writer.Line($"/// Compares the layout of every generated structure with the C compiler's, which the layout library <c>{layouts.NativeName}</c>");
        writer.Line("/// reports: the size and alignment of each structure, and the size and offset of each member (ADR 0036).");
        writer.Line("/// </summary>");
        writer.Line("[global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClass]");
        writer.Line(RawLayerEmitter.GeneratedCodeAttribute);
        writer.Line("internal sealed unsafe partial class LayoutTests");
        writer.OpenBlock();
        writer.Line("/// <summary>The name of the layout library and of the function it exports.</summary>");
        writer.Line($"private const string LayoutLibraryName = \"{layouts.NativeName}\";");
        writer.Line();
        EmitTestMethod(writer);
        writer.Line();
        EmitReadNativeEntries(writer);
        writer.Line();
        EmitMeasureEntries(writer, layouts);

        foreach (var record in layouts.Records)
        {
            writer.Line();
            EmitMeasureMethod(writer, record);
        }

        writer.Line();
        EmitHelpers(writer);
        writer.CloseBlock();

        return new GeneratedFile(TestFileName, writer.ToString());
    }

    /// <summary>Writes the C entries of a record.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="record">The record.</param>
    private static void EmitNativeEntries(CSharpWriter writer, ProjectedRecordLayout record)
    {
        writer.Line(record.CPath is { } recordPath
            ? $"    JADE_LAYOUT_NESTED_RECORD(\"{record.CName}\", {record.CRoot}, {recordPath}),"
            : $"    JADE_LAYOUT_RECORD(\"{record.CName}\", {record.CRoot}),");

        foreach (var member in record.Members)
        {
            IEnumerable<string> designators = member.IsArray ? [member.CName, $"{member.CName}[0]"] : [member.CName];

            foreach (var designator in designators)
            {
                writer.Line(record.CPath is { } path
                    ? $"    JADE_LAYOUT_NESTED_MEMBER(\"{record.CName}.{designator}\", {record.CRoot}, {path}, {designator}),"
                    : $"    JADE_LAYOUT_MEMBER(\"{record.CName}.{designator}\", {record.CRoot}, {designator}),");
            }
        }
    }

    /// <summary>Writes the test method.</summary>
    /// <param name="writer">The writer.</param>
    private static void EmitTestMethod(CSharpWriter writer)
    {
        writer.Line("/// <summary>Checks that every structure has the size, alignment and member offsets and sizes that the C compiler gives it on this platform.</summary>");
        writer.Line("[global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethod]");
        writer.Line("public void EveryStructureHasTheLayoutOfTheCompiler()");
        writer.OpenBlock();
        writer.Line("var native = ReadNativeEntries();");
        writer.Line("var managed = MeasureEntries();");
        writer.Line("var differences = new global::System.Collections.Generic.List<string>();");
        writer.Line();
        writer.Line("foreach (var (name, entry) in managed)");
        writer.OpenBlock();
        writer.Line("if (!native.Remove(name, out var expected))");
        writer.OpenBlock();
        writer.Line("differences.Add($\"{name}: missing from the layout library\");");
        writer.CloseBlock();
        writer.Line("else if (entry != expected)");
        writer.OpenBlock();
        writer.Line("differences.Add($\"{name}: {Describe(expected)} in C, {Describe(entry)} in C#\");");
        writer.CloseBlock();
        writer.CloseBlock();
        writer.Line();
        writer.Line("var extra = new global::System.Collections.Generic.List<string>(native.Keys);");
        writer.Line();
        writer.Line("extra.Sort(global::System.StringComparer.Ordinal);");
        writer.Line();
        writer.Line("foreach (var name in extra)");
        writer.OpenBlock();
        writer.Line("differences.Add($\"{name}: only in the layout library\");");
        writer.CloseBlock();
        writer.Line();
        writer.Line("global::Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsNotEmpty(managed);");
        writer.Line("global::Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsEmpty(");
        writer.Line("    differences,");
        writer.Line("    $\"{differences.Count} differences; names that are missing on one side mean a layout library older than the bindings: rebuild it with 'dotnet run scripts/build-native.cs'.\\n{string.Join('\\n', differences)}\");");
        writer.CloseBlock();
    }

    /// <summary>Writes the method that reads the entries of the layout library.</summary>
    /// <param name="writer">The writer.</param>
    private static void EmitReadNativeEntries(CSharpWriter writer)
    {
        writer.Line("/// <summary>Reads the entries of the layout library, built for this host next to the tests.</summary>");
        writer.Line("/// <returns>The entries, by name.</returns>");
        writer.Line("private static global::System.Collections.Generic.Dictionary<string, Entry> ReadNativeEntries()");
        writer.OpenBlock();
        writer.Line("if (!global::System.Runtime.InteropServices.NativeLibrary.TryLoad(LayoutLibraryName, typeof(LayoutTests).Assembly, global::System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory, out var library))");
        writer.OpenBlock();
        writer.Line("global::Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Inconclusive($\"The {LayoutLibraryName} library is not built for this host: run 'dotnet run scripts/build-native.cs'.\");");
        writer.CloseBlock();
        writer.Line();
        writer.Line("var entries = new global::System.Collections.Generic.Dictionary<string, Entry>(global::System.StringComparer.Ordinal);");
        writer.Line("var function = (delegate* unmanaged[Cdecl]<NativeEntry*>)global::System.Runtime.InteropServices.NativeLibrary.GetExport(library, LayoutLibraryName);");
        writer.Line();
        writer.Line("// The table ends with an entry without name.");
        writer.Line("for (var native = function(); native->Name != null; native++)");
        writer.OpenBlock();
        writer.Line("entries.Add(global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8((nint)native->Name)!, new Entry(native->Size, native->Alignment, native->Offset));");
        writer.CloseBlock();
        writer.Line();
        writer.Line("return entries;");
        writer.CloseBlock();
    }

    /// <summary>Writes the method that measures every record available on the running platform.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="layouts">The layout tests.</param>
    private static void EmitMeasureEntries(CSharpWriter writer, ProjectedLayouts layouts)
    {
        writer.Line("/// <summary>Measures the C# layout of every structure available on this platform.</summary>");
        writer.Line("/// <returns>The entries, in the order of the C side.</returns>");
        writer.Line("private static global::System.Collections.Generic.List<(string Name, Entry Entry)> MeasureEntries()");
        writer.OpenBlock();
        writer.Line("var entries = new global::System.Collections.Generic.List<(string Name, Entry Entry)>();");
        writer.Line();

        foreach (var record in layouts.Records)
        {
            if (GetManagedCondition(record.Availability) is { } condition)
            {
                writer.Line($"if ({condition})");
                writer.OpenBlock();
                writer.Line($"{record.MethodName}(entries);");
                writer.CloseBlock();
            }
            else
            {
                writer.Line($"{record.MethodName}(entries);");
            }
        }

        writer.Line();
        writer.Line("return entries;");
        writer.CloseBlock();
    }

    /// <summary>Writes the method that measures one record.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="record">The record.</param>
    /// <remarks>
    /// The offsets and sizes are differences of addresses in a local of the type, so that a member
    /// of any type is measured the same way, pointers, inline arrays and function pointers included.
    /// </remarks>
    private static void EmitMeasureMethod(CSharpWriter writer, ProjectedRecordLayout record)
    {
        var alignment = record.CPath is null ? $"AlignmentOf<{record.Type}>()" : "0";

        writer.Line($"/// <summary>Measures <c>{record.CName}</c>.</summary>");
        writer.Line("/// <param name=\"entries\">Receives the entries of the record and its members.</param>");
        writer.Line($"private static void {record.MethodName}(global::System.Collections.Generic.List<(string Name, Entry Entry)> entries)");
        writer.OpenBlock();
        writer.Line($"var value = default({record.Type});");
        writer.Line("var start = (byte*)&value;");
        writer.Line();
        writer.Line($"entries.Add((\"{record.CName}\", new Entry((nuint)sizeof({record.Type}), {alignment}, 0)));");

        foreach (var member in record.Members)
        {
            writer.Line($"entries.Add(Member(\"{record.CName}.{member.CName}\", start, &value.{member.Name}, &value.{member.Name} + 1));");

            if (member.IsArray)
            {
                writer.Line($"entries.Add(Member(\"{record.CName}.{member.CName}[0]\", start, &value.{member.Name}[0], &value.{member.Name}[0] + 1));");
            }
        }

        writer.CloseBlock();
    }

    /// <summary>Writes the entry types and the helper methods, which are the same in every library.</summary>
    /// <param name="writer">The writer.</param>
    private static void EmitHelpers(CSharpWriter writer)
    {
        writer.Line("/// <summary>Creates the entry of a member.</summary>");
        writer.Line("/// <param name=\"name\">The name of the entry.</param>");
        writer.Line("/// <param name=\"start\">The start of the record.</param>");
        writer.Line("/// <param name=\"member\">The start of the member.</param>");
        writer.Line("/// <param name=\"end\">The end of the member.</param>");
        writer.Line("/// <returns>The entry.</returns>");
        writer.Line("private static (string Name, Entry Entry) Member(string name, byte* start, void* member, void* end)");
        writer.OpenBlock();
        writer.Line("return (name, new Entry((nuint)((byte*)end - (byte*)member), 0, (nuint)((byte*)member - start)));");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <summary>Gets the alignment of a type: the offset at which a sequential structure places it after one byte.</summary>");
        writer.Line("/// <typeparam name=\"T\">The type.</typeparam>");
        writer.Line("/// <returns>The alignment, in bytes.</returns>");
        writer.Line("private static nuint AlignmentOf<T>()");
        writer.Line("    where T : unmanaged");
        writer.OpenBlock();
        writer.Line("return (nuint)(sizeof(AlignmentProbe<T>) - sizeof(T));");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <summary>Describes an entry for a difference.</summary>");
        writer.Line("/// <param name=\"entry\">The entry.</param>");
        writer.Line("/// <returns>The description.</returns>");
        writer.Line("private static string Describe(Entry entry)");
        writer.OpenBlock();
        writer.Line("return global::System.FormattableString.Invariant($\"size {entry.Size}, alignment {entry.Alignment}, offset {entry.Offset}\");");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <summary>The layout of a record or a member: its size, its alignment (0 for members and anonymous records), and its offset in its record.</summary>");
        writer.Line("/// <param name=\"Size\">The size, in bytes.</param>");
        writer.Line("/// <param name=\"Alignment\">The alignment, in bytes, or 0.</param>");
        writer.Line("/// <param name=\"Offset\">The offset, in bytes, or 0 for a record.</param>");
        writer.Line("private readonly record struct Entry(nuint Size, nuint Alignment, nuint Offset);");
        writer.Line();
        writer.Line("/// <summary>Maps <c>jade_layout_entry</c> of <c>build/layout/jade_layout.h</c>.</summary>");
        writer.Line("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential)]");
        writer.Line("private struct NativeEntry");
        writer.OpenBlock();
        writer.Line("/// <summary>The name of the entry, or null at the end of the table.</summary>");
        writer.Line("public byte* Name;");
        writer.Line();
        writer.Line("/// <summary>The size, in bytes.</summary>");
        writer.Line("public nuint Size;");
        writer.Line();
        writer.Line("/// <summary>The alignment of a named record, in bytes, or 0.</summary>");
        writer.Line("public nuint Alignment;");
        writer.Line();
        writer.Line("/// <summary>The offset of a member in its record, in bytes, or 0.</summary>");
        writer.Line("public nuint Offset;");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <summary>A structure that places a type after one byte, at its alignment.</summary>");
        writer.Line("/// <typeparam name=\"T\">The type.</typeparam>");
        writer.Line("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential)]");
        writer.Line("private struct AlignmentProbe<T>");
        writer.Line("    where T : unmanaged");
        writer.OpenBlock();
        writer.Line("/// <summary>The byte before the value.</summary>");
        writer.Line("public byte Byte;");
        writer.Line();
        writer.Line("/// <summary>The value, at the alignment of its type.</summary>");
        writer.Line("public T Value;");
        writer.CloseBlock();
    }

    /// <summary>Gets the preprocessor condition of the platforms a record is available on.</summary>
    /// <param name="availability">The platforms.</param>
    /// <returns>The condition, or <see langword="null"/> when the record is available everywhere.</returns>
    private static string? GetNativeCondition(Platforms availability)
    {
        return availability == Platforms.All
            ? null
            : availability == Platforms.Native
            ? $"!defined({_platforms.Single(static platform => platform.Platform == Platforms.Browser).Macro})"
            : string.Join(" || ", _platforms.Where(platform => availability.HasFlag(platform.Platform)).Select(static platform => $"defined({platform.Macro})"));
    }

    /// <summary>Gets the C# condition of the platforms a record is available on, which the platform analyzer understands.</summary>
    /// <param name="availability">The platforms.</param>
    /// <returns>The condition, or <see langword="null"/> when the record is available everywhere.</returns>
    private static string? GetManagedCondition(Platforms availability)
    {
        return availability == Platforms.All
            ? null
            : availability == Platforms.Native
            ? "!global::System.OperatingSystem.IsBrowser()"
            : string.Join(" || ", _platforms.Where(platform => availability.HasFlag(platform.Platform)).Select(static platform => $"global::System.OperatingSystem.{platform.Check}()"));
    }

    /// <summary>Gets the path of a repository file relative to a repository directory, as a quoted <c>#include</c> resolves it.</summary>
    /// <param name="directory">The directory, relative to the repository root with <c>/</c> separators.</param>
    /// <param name="path">The file, relative to the repository root with <c>/</c> separators.</param>
    /// <returns>The relative path, such as <c>../miniaudio/config.h</c>.</returns>
    private static string GetRelativePath(string directory, string path)
    {
        var from = directory.Split('/');
        var to = path.Split('/');
        var common = 0;

        while (common < from.Length && common < to.Length - 1 && string.Equals(from[common], to[common], StringComparison.Ordinal))
        {
            common++;
        }

        return string.Join('/', Enumerable.Repeat("..", from.Length - common).Concat(to.Skip(common)));
    }
}
