using System.Diagnostics;
using System.Globalization;
using Jade.BindingGenerator.Projection;
using Jade.BindingGenerator.Targets;

namespace Jade.BindingGenerator.Emission;

/// <summary>Writes the raw layer of an interop library: one file per C# type (ADR 0027).</summary>
/// <remarks>
/// The output depends only on the projected library: ordinal ordering, invariant formatting, LF
/// line endings and no timestamp or path of the machine (ADR 0007). Framework types are written
/// with <c>global::</c> so that the files depend on no using directive of the project.
/// </remarks>
internal static class RawLayerEmitter
{
    /// <summary>The tool named by <c>[GeneratedCode]</c>.</summary>
    private const string Tool = "Jade.BindingGenerator";

    /// <summary>The version named by <c>[GeneratedCode]</c>; it changes when the generator's output conventions do.</summary>
    private const string ToolVersion = "1.0.0";

    /// <summary>The attribute that every generated type carries (ADR 0009).</summary>
    private const string GeneratedCodeAttribute = $"[global::System.CodeDom.Compiler.GeneratedCode(\"{Tool}\", \"{ToolVersion}\")]";

    /// <summary>The platform names of the platform attributes, in the order of ADR 0012.</summary>
    private static readonly (Platforms Platform, string Name)[] _platformNames =
    [
        (Platforms.Windows, "windows"),
        (Platforms.Linux, "linux"),
        (Platforms.MacOS, "macos"),
        (Platforms.IOS, "ios"),
        (Platforms.Android, "android"),
        (Platforms.Browser, "browser"),
    ];

    /// <summary>Writes the files of a library's raw layer.</summary>
    /// <param name="library">The projected library.</param>
    /// <returns>The files, ordered by name.</returns>
    public static IReadOnlyList<GeneratedFile> Emit(ProjectedLibrary library)
    {
        return [.. library.Types
            .Select(type => new GeneratedFile($"{type.Name}.g.cs", EmitFile(library, writer => EmitType(writer, type))))
            .Append(new GeneratedFile($"{RawProjection.NativeMethodsClass}.g.cs", EmitFile(library, writer => EmitNativeMethods(writer, library))))
            .OrderBy(static file => file.Name, StringComparer.Ordinal)];
    }

    /// <summary>Writes a file: its header, its namespace and one type.</summary>
    /// <param name="library">The projected library.</param>
    /// <param name="emitType">Writes the type.</param>
    /// <returns>The source text.</returns>
    private static string EmitFile(ProjectedLibrary library, Action<CSharpWriter> emitType)
    {
        var writer = new CSharpWriter();

        writer.Line("// <auto-generated/>");
        writer.Line($"// Generated by scripts/binding-generator.cs from interop/{library.Namespace}/bindings.json. Do not edit:");
        writer.Line("// change the generator or its configuration and regenerate.");
        writer.Line();

        // Generated files start with nullable annotations disabled.
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line($"namespace {library.Namespace};");
        writer.Line();
        emitType(writer);

        return writer.ToString();
    }

    /// <summary>Writes a type.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The type.</param>
    private static void EmitType(CSharpWriter writer, ProjectedType type)
    {
        switch (type)
        {
            case ProjectedEnum projectedEnum:
                EmitEnum(writer, projectedEnum);
                break;

            case ProjectedHandle handle:
                EmitHandle(writer, handle);
                break;

            case ProjectedBoolean boolean:
                EmitBoolean(writer, boolean);
                break;

            case ProjectedStructure structure:
                EmitStructure(writer, structure);
                break;

            default:
                throw new UnreachableException($"Unknown projected type {type}.");
        }
    }

    /// <summary>Writes an enum or a <c>[Flags]</c> enum.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The enum.</param>
    private static void EmitEnum(CSharpWriter writer, ProjectedEnum type)
    {
        EmitTypeHeader(writer, type, $"Maps <c>{type.CName}</c>.");

        if (type.IsFlags)
        {
            writer.Line("[global::System.Flags]");
        }

        writer.Line($"{GetAccessibility(type.IsPublic)} enum {type.Name} : {type.UnderlyingType}");
        writer.OpenBlock();

        for (var i = 0; i < type.Values.Count; i++)
        {
            var value = type.Values[i];

            if (i > 0)
            {
                writer.Line();
            }

            writer.Line($"/// <summary>Maps <c>{value.CName}</c>.</summary>");

            if (value.Availability != type.Availability)
            {
                EmitPlatformAttributes(writer, value.Availability);
            }

            writer.Line(string.Create(CultureInfo.InvariantCulture, $"{value.Name} = 0x{value.Value.ToString($"X{type.Size * 2}", CultureInfo.InvariantCulture)},"));
        }

        writer.CloseBlock();
    }

    /// <summary>Writes a handle: a <c>readonly</c> structure over the native pointer, with value equality (ADR 0009 and 0028).</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The handle.</param>
    private static void EmitHandle(CSharpWriter writer, ProjectedHandle type)
    {
        EmitTypeHeader(writer, type, $"Maps <c>{type.CName}</c>, a handle to an object of the native library.");
        writer.Line($"{GetAccessibility(type.IsPublic)} readonly partial struct {type.Name} : global::System.IEquatable<{type.Name}>");
        writer.OpenBlock();
        writer.Line($"/// <summary>Initializes a new instance of the <see cref=\"{type.Name}\"/> struct from a native pointer.</summary>");
        writer.Line($"/// <param name=\"handle\">The <c>{type.CName}</c> pointer, or zero for no object.</param>");
        writer.Line($"public {type.Name}(nint handle)");
        writer.OpenBlock();
        writer.Line("Handle = handle;");
        writer.CloseBlock();
        writer.Line();
        writer.Line($"/// <summary>Gets the <c>{type.CName}</c> pointer, or zero for no object.</summary>");
        writer.Line("public nint Handle { get; }");
        writer.Line();
        EmitEqualityOperators(writer, type.Name, "Handle", "handles", "both point to the same object or are both zero");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public bool Equals({type.Name} other)");
        writer.OpenBlock();
        writer.Line("return Handle == other.Handle;");
        writer.CloseBlock();
        writer.Line();
        EmitObjectOverrides(writer, type.Name, "Handle.GetHashCode()");
        writer.CloseBlock();
    }

    /// <summary>Writes a boolean structure: an integer of the C API's size, converted implicitly from and to <see langword="bool"/> (ADR 0027).</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The boolean.</param>
    private static void EmitBoolean(CSharpWriter writer, ProjectedBoolean type)
    {
        EmitTypeHeader(writer, type, $"Maps <c>{type.CName}</c>, an integer that holds a boolean.");
        writer.Line($"{GetAccessibility(type.IsPublic)} readonly partial struct {type.Name} : global::System.IEquatable<{type.Name}>");
        writer.OpenBlock();
        writer.Line("/// <summary>The integer: zero for <see langword=\"false\"/>, anything else for <see langword=\"true\"/>.</summary>");
        writer.Line($"private readonly {type.UnderlyingType} _value;");
        writer.Line();
        writer.Line($"/// <summary>Initializes a new instance of the <see cref=\"{type.Name}\"/> struct.</summary>");
        writer.Line("/// <param name=\"value\">The boolean, stored as 1 or 0.</param>");
        writer.Line($"public {type.Name}(bool value)");
        writer.OpenBlock();
        writer.Line($"_value = value ? ({type.UnderlyingType})1 : ({type.UnderlyingType})0;");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <summary>Gets the boolean; any non-zero integer is <see langword=\"true\"/>, as in C.</summary>");
        writer.Line("public bool Value => _value != 0;");
        writer.Line();
        writer.Line("/// <summary>Converts to a <see langword=\"bool\"/>.</summary>");
        writer.Line("/// <param name=\"value\">The value to convert.</param>");
        writer.Line("/// <returns>The boolean.</returns>");
        writer.Line($"public static implicit operator bool({type.Name} value)");
        writer.OpenBlock();
        writer.Line("return value.Value;");
        writer.CloseBlock();
        writer.Line();
        writer.Line($"/// <summary>Converts from a <see langword=\"bool\"/>.</summary>");
        writer.Line("/// <param name=\"value\">The boolean.</param>");
        writer.Line("/// <returns>The value, stored as 1 or 0.</returns>");
        writer.Line($"public static implicit operator {type.Name}(bool value)");
        writer.OpenBlock();
        writer.Line($"return new {type.Name}(value);");
        writer.CloseBlock();
        writer.Line();
        EmitEqualityOperators(writer, type.Name, "Value", "values", "both are true or both are false");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public bool Equals({type.Name} other)");
        writer.OpenBlock();
        writer.Line("return Value == other.Value;");
        writer.CloseBlock();
        writer.Line();
        EmitObjectOverrides(writer, type.Name, "Value.GetHashCode()");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line("public override string ToString()");
        writer.OpenBlock();
        writer.Line("return Value.ToString();");
        writer.CloseBlock();
        writer.CloseBlock();
    }

    /// <summary>Writes a structure: a public value structure, or an internal raw structure without member comments (ADR 0028).</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The structure.</param>
    private static void EmitStructure(CSharpWriter writer, ProjectedStructure type)
    {
        var isUnsafe = type.Fields.Any(static field => field.Type.Contains('*', StringComparison.Ordinal));

        EmitTypeHeader(writer, type, $"Maps <c>{type.CName}</c>.");

        // The explicit layout states the C contract; the compiler also takes it as the mark of an
        // interop type, whose fields native code writes, and does not report them as never assigned.
        writer.Line("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Sequential)]");
        writer.Line($"{GetAccessibility(type.IsPublic)} {(isUnsafe ? "unsafe " : string.Empty)}partial struct {type.Name}");
        writer.OpenBlock();

        foreach (var field in type.Fields)
        {
            if (type.IsPublic)
            {
                if (field != type.Fields[0])
                {
                    writer.Line();
                }

                writer.Line($"/// <summary>Maps <c>{type.CName}.{field.CName}</c>.</summary>");
            }

            writer.Line($"{GetAccessibility(field.IsPublic || !type.IsPublic)} {field.Type} {field.Name};");
        }

        if (type.Defaults.Count > 0)
        {
            var defaults = type.InitializerCName is { } initializer ? $"<c>{initializer}</c>" : "its C declaration";

            writer.Line();
            writer.Line($"/// <summary>Initializes a new instance of the <see cref=\"{type.Name}\"/> struct with the defaults of {defaults}.</summary>");
            writer.Line($"public {type.Name}()");
            writer.OpenBlock();

            foreach (var assignment in type.Defaults)
            {
                writer.Line($"{assignment.Target} = {assignment.Value};");
            }

            writer.CloseBlock();
        }

        writer.CloseBlock();
    }

    /// <summary>Writes the internal class of the constants and the functions, which keep their C names (ADR 0028).</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="library">The projected library.</param>
    private static void EmitNativeMethods(CSharpWriter writer, ProjectedLibrary library)
    {
        writer.Line("/// <summary>The constants and functions of the C API, with their C names.</summary>");
        writer.Line(GeneratedCodeAttribute);
        writer.Line($"internal static unsafe partial class {RawProjection.NativeMethodsClass}");
        writer.OpenBlock();
        writer.Line("/// <summary>The name the functions are imported from.</summary>");
        writer.Line($"private const string LibraryName = \"{library.LibraryName}\";");

        foreach (var constant in library.Constants)
        {
            writer.Line();
            writer.Line($"/// <summary>Maps <c>{constant.CName}</c>.</summary>");
            EmitPlatformAttributes(writer, constant.Availability);
            writer.Line(constant.IsConst
                ? $"public const {constant.Type} {constant.CName} = {constant.Value};"
                : $"public static {constant.Type} {constant.CName} => {constant.Value};");
        }

        foreach (var function in library.Functions)
        {
            writer.Line();
            writer.Line($"/// <summary>Maps <c>{function.CName}</c>.</summary>");
            writer.Line("[global::System.Runtime.InteropServices.LibraryImport(LibraryName)]");
            writer.Line("[global::System.Runtime.InteropServices.UnmanagedCallConv(CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]");
            EmitPlatformAttributes(writer, function.Availability);
            writer.Line($"public static partial {function.ReturnType} {function.CName}({string.Join(", ", function.Parameters.Select(static parameter => $"{parameter.Type} {parameter.Name}"))});");
        }

        writer.CloseBlock();
    }

    /// <summary>Writes the summary and the attributes of a type.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="type">The type.</param>
    /// <param name="summary">The summary, as XML documentation text.</param>
    private static void EmitTypeHeader(CSharpWriter writer, ProjectedType type, string summary)
    {
        writer.Line($"/// <summary>{summary}</summary>");
        writer.Line(GeneratedCodeAttribute);
        EmitPlatformAttributes(writer, type.Availability);
    }

    /// <summary>Writes the platform attributes of a declaration that some platforms lack (ADR 0027).</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="availability">The platforms the declaration is available on.</param>
    private static void EmitPlatformAttributes(CSharpWriter writer, Platforms availability)
    {
        if (availability == Platforms.All)
        {
            return;
        }

        if (availability == Platforms.Native)
        {
            writer.Line("[global::System.Runtime.Versioning.UnsupportedOSPlatform(\"browser\")]");
            return;
        }

        foreach (var (platform, name) in _platformNames.Where(platform => availability.HasFlag(platform.Platform)))
        {
            writer.Line($"[global::System.Runtime.Versioning.SupportedOSPlatform(\"{name}\")]");
        }
    }

    /// <summary>Writes the equality operators of a structure that compares one member.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="typeName">The name of the structure.</param>
    /// <param name="member">The member compared.</param>
    /// <param name="noun">The plural noun of the compared values, for the documentation.</param>
    /// <param name="equalWhen">When two values are equal, for the documentation.</param>
    private static void EmitEqualityOperators(CSharpWriter writer, string typeName, string member, string noun, string equalWhen)
    {
        writer.Line($"/// <summary>Compares two {noun}.</summary>");
        writer.Line("/// <param name=\"left\">The first value.</param>");
        writer.Line("/// <param name=\"right\">The second value.</param>");
        writer.Line($"/// <returns><see langword=\"true\"/> when {equalWhen}.</returns>");
        writer.Line($"public static bool operator ==({typeName} left, {typeName} right)");
        writer.OpenBlock();
        writer.Line($"return left.{member} == right.{member};");
        writer.CloseBlock();
        writer.Line();
        writer.Line($"/// <summary>Compares two {noun}.</summary>");
        writer.Line("/// <param name=\"left\">The first value.</param>");
        writer.Line("/// <param name=\"right\">The second value.</param>");
        writer.Line($"/// <returns><see langword=\"false\"/> when {equalWhen}.</returns>");
        writer.Line($"public static bool operator !=({typeName} left, {typeName} right)");
        writer.OpenBlock();
        writer.Line($"return left.{member} != right.{member};");
        writer.CloseBlock();
    }

    /// <summary>Writes the overrides of <see cref="object.Equals(object)"/> and <see cref="object.GetHashCode"/>.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="typeName">The name of the structure.</param>
    /// <param name="hashCode">The expression of the hash code.</param>
    private static void EmitObjectOverrides(CSharpWriter writer, string typeName, string hashCode)
    {
        writer.Line("/// <inheritdoc/>");
        writer.Line("public override bool Equals(object? obj)");
        writer.OpenBlock();
        writer.Line($"return obj is {typeName} other && Equals(other);");
        writer.CloseBlock();
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line("public override int GetHashCode()");
        writer.OpenBlock();
        writer.Line($"return {hashCode};");
        writer.CloseBlock();
    }

    /// <summary>Gets the accessibility keyword of a type or a member.</summary>
    /// <param name="isPublic">Whether it is public.</param>
    /// <returns><c>public</c> or <c>internal</c>.</returns>
    private static string GetAccessibility(bool isPublic)
    {
        return isPublic ? "public" : "internal";
    }
}
