using System.Globalization;
using System.Text;

/// <summary>
/// Turns a <see cref="LibraryModel"/> into C# files following ADR-0006: a raw 1:1 import per function, friendly
/// overloads where parameters are annotated, constants, enums, structs and handles with instance methods. The output
/// only depends on the model, so it is byte-identical for identical inputs.
/// </summary>
internal sealed class CSharpEmitter
{
    /// <summary>The first line of every generated file.</summary>
    public const string Header = "// <auto-generated/> by scripts/generate-bindings.cs. Do not edit: change the generator or its config and regenerate.";

    private readonly LibraryModel _model;
    private readonly ImportStyle _importStyle;
    private readonly Dictionary<string, string> _managedNames = new(StringComparer.Ordinal);
    private readonly Dictionary<string, EnumModel> _enums = new(StringComparer.Ordinal);
    private readonly Dictionary<string, StructModel> _structs = new(StringComparer.Ordinal);
    private readonly SortedSet<string> _usings = new(StringComparer.Ordinal);

    /// <summary>Creates an emitter.</summary>
    /// <param name="model">The library to emit.</param>
    /// <param name="importStyle">How raw functions are imported.</param>
    public CSharpEmitter(LibraryModel model, ImportStyle importStyle)
    {
        _model = model;
        _importStyle = importStyle;
        foreach (var (native, managed) in model.Enums.Select(e => (e.NativeName, e.Name))
            .Concat(model.Structs.Select(s => (s.NativeName, s.Name)))
            .Concat(model.Handles.Select(h => (h.NativeName, h.Name))))
        {
            _managedNames.Add(native, managed);
        }

        foreach (var enumModel in model.Enums)
        {
            _enums.Add(enumModel.NativeName, enumModel);
        }

        foreach (var structModel in model.Structs)
        {
            _structs.Add(structModel.NativeName, structModel);
        }
    }

    /// <summary>Renders every file of the library.</summary>
    /// <returns>File contents by file name, in ordinal order.</returns>
    /// <exception cref="InvalidOperationException">Two declarations map to the same C# name.</exception>
    public IReadOnlyDictionary<string, string> Emit()
    {
        CheckClassMembers();
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        void Add(string name, string content)
        {
            if (!files.TryAdd(name, content))
            {
                throw new InvalidOperationException($"{_model.Name}: two declarations produce {name}; rename one in the config.");
            }
        }

        var documentClass = true;
        foreach (var (group, source) in _model.Groups)
        {
            var functions = _model.Functions.Where(f => f.Group == group).ToList();
            var constants = _model.Constants.Where(c => c.Group == group).ToList();
            if (functions.Count == 0 && constants.Count == 0)
            {
                continue;
            }

            Add($"{_model.FunctionsClass}.{group}.g.cs", EmitGroup(source, functions, constants, documentClass));
            documentClass = false;
        }

        foreach (var enumModel in _model.Enums)
        {
            Add($"{enumModel.Name}.g.cs", EmitEnum(enumModel));
        }

        foreach (var structModel in _model.Structs)
        {
            Add($"{structModel.Name}.g.cs", EmitStruct(structModel));
        }

        foreach (var handle in _model.Handles)
        {
            Add($"{handle.Name}.g.cs", EmitHandle(handle));
        }

        return files;
    }

    /// <summary>Returns whether an array field of this element type is a C# <c>fixed</c> buffer rather than an <c>[InlineArray]</c>.</summary>
    /// <param name="element">The array's element type.</param>
    /// <returns><see langword="true"/> for the primitives C# fixed buffers accept.</returns>
    public static bool IsFixedBufferElement(TypeRef element) =>
        element.Kind == TypeKind.Primitive && element.Primitive is not (PrimitiveType.NInt or PrimitiveType.NUInt or PrimitiveType.CLong or PrimitiveType.CULong);

    /// <summary>Returns the name of a handle's instance method for a function taking the handle first.</summary>
    /// <param name="function">The function's C# name, for example <c>GetWindowSize</c>.</param>
    /// <param name="handle">The handle's C# name, for example <c>Window</c>.</param>
    /// <returns>The name without the handle right after its leading verb (<c>GetSize</c>), or unchanged.</returns>
    public static string InstanceName(string function, string handle)
    {
        static bool Boundary(string name, int index) => index == name.Length || !char.IsLower(name[index]);

        if (function.StartsWith(handle, StringComparison.Ordinal) && Boundary(function, handle.Length) && function.Length > handle.Length)
        {
            return function[handle.Length..];
        }

        var verb = 1;
        while (verb < function.Length && !char.IsUpper(function[verb]))
        {
            verb++;
        }

        return function.AsSpan(verb).StartsWith(handle, StringComparison.Ordinal) && Boundary(function, verb + handle.Length)
            ? function[..verb] + function[(verb + handle.Length)..]
            : function;
    }

    // Functions, their private imports and constants share the static class: a C# name may only come from one C declaration.
    private void CheckClassMembers()
    {
        var owners = _model.Functions.Select(f => (f.Name, f.NativeName))
            .Concat(_model.Functions.Where(HasFunctionPointer).Select(f => (Name: ImportName(f), f.NativeName)))
            .Concat(_model.Constants.Select(c => (c.Name, c.NativeName)));
        foreach (var clash in owners.GroupBy(o => o.Name, StringComparer.Ordinal).Where(g => g.Count() > 1))
        {
            throw new InvalidOperationException($"{_model.Name}: {string.Join(", ", clash.Select(c => c.NativeName))} all map to {_model.FunctionsClass}.{clash.Key}; add Renames.");
        }
    }

    private string EmitGroup(string source, IReadOnlyList<FunctionModel> functions, IReadOnlyList<ConstantModel> constants, bool documentClass)
    {
        var writer = new CodeWriter();
        var shadowed = _model.Functions.Select(f => f.Name)
            .Concat(_model.Functions.Where(HasFunctionPointer).Select(ImportName))
            .Concat(_model.Constants.Select(c => c.Name))
            .ToHashSet(StringComparer.Ordinal);
        if (documentClass)
        {
            DocWriter.Single(writer, "summary", $"Functions and constants of {_model.Name}, imported from `jade_native`.");
        }

        writer.Open($"public static unsafe partial class {_model.FunctionsClass}");
        writer.Line($"// Declarations from {source}.");
        foreach (var constant in constants)
        {
            writer.Line();
            EmitConstant(writer, constant, shadowed);
        }

        foreach (var function in functions)
        {
            writer.Line();
            EmitRawFunction(writer, function, shadowed);
            if (HasFriendlyForm(function))
            {
                writer.Line();
                EmitFriendlyFunction(writer, function, shadowed);
            }
        }

        writer.Close();
        return Finish(writer);
    }

    private void EmitConstant(CodeWriter writer, ConstantModel constant, HashSet<string> shadowed)
    {
        var value = constant.IsString && !constant.Text!.Contains('`', StringComparison.Ordinal) ? $"The value is `{constant.Text}`." : null;
        WriteTypeDocs(writer, constant.NativeName, constant.Documentation, value);
        WritePlatformAttributes(writer, constant.SupportedPlatforms, constant.UnsupportedPlatforms);
        if (constant.IsString)
        {
            writer.Line($"public static ReadOnlySpan<byte> {constant.Name} => {StringLiteral(constant.Text!)}u8;");
            return;
        }

        var type = constant.Type;
        if (type.Is(PrimitiveType.NUInt) && constant.Integer == ulong.MaxValue)
        {
            // SIZE_MAX depends on the pointer size, and C# has no constant for nuint.MaxValue.
            writer.Line($"public static nuint {constant.Name} => nuint.MaxValue;");
            return;
        }

        if (type.Kind == TypeKind.Named)
        {
            var enumModel = _enums[type.Name!];
            var number = IntegerLiteral(enumModel.Underlying, constant.Integer, constant.NativeName);
            var name = TypeName(type, shadowed);
            writer.Line($"public const {name} {constant.Name} = ({name}){(number.StartsWith('-') ? $"({number})" : number)};");
            return;
        }

        var literal = type.Primitive switch
        {
            PrimitiveType.Bool => constant.Integer != 0 ? "true" : "false",
            PrimitiveType.Single => FloatLiteral((float)constant.Float, "F"),
            PrimitiveType.Double => FloatLiteral(constant.Float, "D"),
            _ => IntegerLiteral(type.Primitive, constant.Integer, constant.NativeName),
        };
        writer.Line($"public const {Keyword(type.Primitive)} {constant.Name} = {literal};");
    }

    private void EmitRawFunction(CodeWriter writer, FunctionModel function, HashSet<string> shadowed)
    {
        WriteFunctionDocs(writer, function, function.Parameters, generic: false);
        var returnType = TypeName(function.Return, shadowed);
        var visibility = "public";
        if (HasFunctionPointer(function))
        {
            // ADR-0016: browser-wasm rejects function pointer types in P/Invoke signatures, so the import passes them as
            // nint and this public 1:1 method keeps the typed signature. The casts cost nothing.
            var typed = string.Join(", ", function.Parameters.Select(p => $"{TypeName(p.Type, shadowed)} {p.Name}"));
            var arguments = string.Join(", ", function.Parameters.Select(p => p.Type.Kind == TypeKind.FunctionPointer ? "(nint)" + p.Name : p.Name));
            var call = $"{ImportName(function)}({arguments})";
            WritePlatformAttributes(writer, function);
            writer.Line($"public static {returnType} {function.Name}({typed}) => {(function.Return.Kind == TypeKind.FunctionPointer ? $"({returnType}){call}" : call)};");
            writer.Line();
            visibility = "private";
        }

        var importReturn = ImportTypeName(function.Return, shadowed);
        _usings.Add("System.Runtime.InteropServices");
        if (_importStyle == ImportStyle.DllImport)
        {
            var parameters = string.Join(", ", function.Parameters.Select(p => $"{ImportTypeName(p.Type, shadowed)} {p.Name}"));
            writer.Line($"[DllImport(\"jade_native\", EntryPoint = \"{function.NativeName}\", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]");
            if (visibility == "public")
            {
                WritePlatformAttributes(writer, function);
            }

            writer.Line($"{visibility} static extern {importReturn} {ImportName(function)}({parameters});");
        }
        else
        {
            // The LibraryImport generator refuses a bare bool even with runtime marshalling disabled (SYSLIB1051): U1 makes
            // it pass a C bool as one byte, and it reads a returned one as `!= 0`.
            _usings.Add("System.Runtime.CompilerServices");
            writer.Line($"[LibraryImport(\"jade_native\", EntryPoint = \"{function.NativeName}\")]");
            writer.Line("[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
            if (visibility == "public")
            {
                WritePlatformAttributes(writer, function);
            }

            if (function.Return.Is(PrimitiveType.Bool))
            {
                writer.Line("[return: MarshalAs(UnmanagedType.U1)]");
            }

            var parameters = string.Join(", ", function.Parameters.Select(p => $"{(p.Type.Is(PrimitiveType.Bool) ? "[MarshalAs(UnmanagedType.U1)] " : string.Empty)}{ImportTypeName(p.Type, shadowed)} {p.Name}"));
            writer.Line($"{visibility} static partial {importReturn} {ImportName(function)}({parameters});");
        }
    }

    private void EmitFriendlyFunction(CodeWriter writer, FunctionModel function, HashSet<string> shadowed)
    {
        var exposed = function.Parameters.Where(p => p.Kind != ParameterKind.Count).ToList();
        WriteFunctionDocs(writer, function, exposed, generic: true);
        WritePlatformAttributes(writer, function);
        var signature = string.Join(", ", exposed.Select(p => $"{FriendlyType(function, p, shadowed)} {p.Name}"));
        CheckLocals(function);
        writer.Open($"public static {TypeName(function.Return, shadowed)} {function.Name}{TypeParameters(function)}({signature}){Constraints(function)}");

        foreach (var parameter in function.Parameters.Where(p => p.Kind == ParameterKind.Out))
        {
            // Cleared first: the callee may leave the value unwritten, typically when it fails.
            writer.Line($"{parameter.Name} = default;");
        }

        foreach (var parameter in function.Parameters.Where(p => p.Kind == ParameterKind.Utf8String))
        {
            writer.Line($"using var {Utf8Local(parameter)} = new NulTerminatedUtf8({parameter.Name}, stackalloc byte[NulTerminatedUtf8.StackLength]);");
        }

        var fixedCount = 0;
        foreach (var parameter in function.Parameters)
        {
            var pointer = parameter.Kind switch
            {
                ParameterKind.None or ParameterKind.Count => null,
                ParameterKind.StringView => "byte*",
                ParameterKind.Span when IsByteSpan(parameter) => TypeParameter(function, parameter) + "*",
                _ => TypeName(parameter.Type, shadowed),
            };
            var initializer = parameter.Kind switch
            {
                ParameterKind.Utf8String => Utf8Local(parameter),
                ParameterKind.In or ParameterKind.Out or ParameterKind.Ref => $"&{parameter.Name}",
                ParameterKind.Span or ParameterKind.StringView => parameter.Name,
                _ => null,
            };
            if (pointer is not null && initializer is not null)
            {
                writer.Line($"fixed ({pointer} {PinnedLocal(parameter)} = {initializer})");
                fixedCount++;
            }
        }

        if (fixedCount > 0)
        {
            writer.Line("{");
            writer.Indent();
        }

        var arguments = function.Parameters.Select(p => p.Kind switch
        {
            ParameterKind.None => p.Name,
            ParameterKind.Count => CountArgument(function, p, shadowed),
            ParameterKind.StringView => StringViewArgument(p, shadowed),
            _ => PinnedLocal(p),
        });
        var call = $"{function.Name}({string.Join(", ", arguments)});";
        writer.Line(function.Return.Kind == TypeKind.Void ? call : "return " + call);

        if (fixedCount > 0)
        {
            writer.Unindent();
            writer.Line("}");
        }

        writer.Close();
    }

    private string EmitEnum(EnumModel enumModel)
    {
        var writer = new CodeWriter();
        var note = enumModel.Members.Count == 0 ? "An identifier: values come from native calls and only compare for equality." : null;
        WriteTypeDocs(writer, enumModel.NativeName, enumModel.Documentation, note);
        WritePlatformAttributes(writer, enumModel.SupportedPlatforms, enumModel.UnsupportedPlatforms);
        if (enumModel.IsFlags)
        {
            writer.Line("[Flags]");
        }

        writer.Open($"public enum {enumModel.Name} : {Keyword(enumModel.Underlying)}");
        var first = true;
        foreach (var member in enumModel.Members)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            DocWriter.Single(writer, "summary", member.Documentation.Summary ?? $"Binds `{member.NativeName}`.");
            WritePlatformAttributes(writer, member.SupportedPlatforms, member.UnsupportedPlatforms);
            writer.Line($"{member.Name} = {EnumValue(enumModel, member.Value)},");
        }

        writer.Close();
        return Finish(writer);
    }

    private string EmitStruct(StructModel structModel)
    {
        var writer = new CodeWriter();
        if (structModel.IsOpaque)
        {
            WriteTypeDocs(writer, structModel.NativeName, structModel.Documentation, "An opaque native type, only used through pointers.");
            WritePlatformAttributes(writer, structModel.SupportedPlatforms, structModel.UnsupportedPlatforms);
            writer.Open($"public partial struct {structModel.Name}");
            writer.Close();
            return Finish(writer);
        }

        _usings.Add("System.Runtime.InteropServices");
        WriteTypeDocs(writer, structModel.NativeName, structModel.Documentation, structModel.NativeName.Contains('.', StringComparison.Ordinal) ? "The anonymous type of that field." : null);
        WritePlatformAttributes(writer, structModel.SupportedPlatforms, structModel.UnsupportedPlatforms);
        writer.Line(structModel.IsUnion ? "[StructLayout(LayoutKind.Explicit)]" : "[StructLayout(LayoutKind.Sequential)]");
        writer.Open($"public unsafe partial struct {structModel.Name}");
        var arrays = structModel.Fields.Where(f => f.Type.Kind == TypeKind.FixedArray && !IsFixedBufferElement(f.Type.Element!)).ToList();
        var shadowed = structModel.Fields.Select(f => f.Name).Concat(arrays.Select(InlineArrayName)).ToHashSet(StringComparer.Ordinal);
        if (shadowed.Count != structModel.Fields.Count + arrays.Count)
        {
            throw new InvalidOperationException($"{structModel.NativeName}: a field name clashes with a generated inline array type; rename the field in the config.");
        }

        var first = true;
        foreach (var field in structModel.Fields)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            WriteFieldDocs(writer, field);
            if (structModel.IsUnion)
            {
                writer.Line("[FieldOffset(0)]");
            }

            if (field.Type.Kind != TypeKind.FixedArray)
            {
                writer.Line($"public {TypeName(field.Type, shadowed)} {field.Name};");
            }
            else if (IsFixedBufferElement(field.Type.Element!))
            {
                writer.Line($"public fixed {TypeName(field.Type.Element!, shadowed)} {field.Name}[{field.Type.Length}];");
            }
            else
            {
                writer.Line($"public {InlineArrayName(field)} {field.Name};");
            }
        }

        if (structModel.Initializers.Count > 0)
        {
            EmitConstructor(writer, structModel, shadowed);
        }

        // C# fixed buffers only hold primitives; other element types get an [InlineArray] of the native length.
        foreach (var field in arrays)
        {
            _usings.Add("System.Runtime.CompilerServices");
            writer.Line();
            DocWriter.Single(writer, "summary", $"The {field.Type.Length} elements of `{structModel.NativeName}.{field.NativeName}`, indexable like an array.");
            writer.Line($"[InlineArray({field.Type.Length})]");
            writer.Open($"public struct {InlineArrayName(field)}");
            writer.Line($"private {TypeName(field.Type.Element!, shadowed)} _element0;");
            writer.Close();
        }

        writer.Close();
        return Finish(writer);
    }

    // `new T()` then sets the fields a valid value needs; `default(T)` still zeroes everything.
    private void EmitConstructor(CodeWriter writer, StructModel structModel, HashSet<string> shadowed)
    {
        var assignments = new List<(string Field, string Value)>();
        foreach (var initializer in structModel.Initializers)
        {
            var owner = structModel;
            var path = new List<string>();
            FieldModel? field = null;
            foreach (var name in initializer.Path)
            {
                if (field is not null)
                {
                    owner = field.Type.Kind == TypeKind.Named && _structs.TryGetValue(field.Type.Name!, out var inner) ? inner
                        : throw new InvalidOperationException($"{structModel.NativeName}: initializer path {string.Join('.', initializer.Path)} goes through a field that is not a struct.");
                }

                field = owner.Fields.FirstOrDefault(f => f.NativeName == name)
                    ?? throw new InvalidOperationException($"{structModel.NativeName}: initializer path {string.Join('.', initializer.Path)} names no field {name}.");
                path.Add(field.Name);
            }

            var enumModel = field!.Type.Kind == TypeKind.Named && _enums.TryGetValue(field.Type.Name!, out var found) ? found
                : throw new InvalidOperationException($"{structModel.NativeName}: initializer path {string.Join('.', initializer.Path)} does not end on an enum field.");
            var member = enumModel.Members.FirstOrDefault(m => m.NativeName == initializer.Member)
                ?? throw new InvalidOperationException($"{structModel.NativeName}: {enumModel.NativeName} has no member {initializer.Member}.");
            assignments.Add((string.Join('.', path), $"{TypeName(field.Type, shadowed)}.{member.Name}"));
        }

        writer.Line();
        var list = string.Join(", ", assignments.Select(a => $"`{a.Field}` to `{a.Value.Replace("global::" + _model.Namespace + ".", string.Empty, StringComparison.Ordinal)}`"));
        DocWriter.Single(writer, "summary", $"Initializes the struct with every field zeroed, except {list}.");
        writer.Open($"public {structModel.Name}()");
        foreach (var (field, value) in assignments)
        {
            writer.Line($"{field} = {value};");
        }

        writer.Close();
    }

    private string EmitHandle(HandleModel handle)
    {
        var writer = new CodeWriter();
        var instanceFunctions = handle.IsForeign ? [] : _model.Functions
            .Where(f => f.Parameters.Count > 0 && f.Parameters[0].Kind == ParameterKind.None && f.Parameters[0].Type is { Kind: TypeKind.Named } first && first.Name == handle.NativeName)
            .ToList();
        // A shortened name that would hide a member of the handle or of object keeps the function's full name instead.
        string[] members = ["Handle", "IsNull", "Equals", "GetHashCode", "GetType", "ToString", "MemberwiseClone", "ReferenceEquals", handle.Name];
        var names = instanceFunctions.ToDictionary(f => f, f => InstanceName(f.Name, handle.Stem) is var name && !members.Contains(name) ? name : f.Name);
        foreach (var clash in names.GroupBy(n => n.Value, StringComparer.Ordinal).Where(g => g.Count() > 1))
        {
            throw new InvalidOperationException($"{handle.NativeName}: {string.Join(", ", clash.Select(f => f.Key.NativeName))} give the instance method {clash.Key}; rename one in the config.");
        }

        var shadowed = names.Values.Concat(["Handle", "IsNull"]).ToHashSet(StringComparer.Ordinal);

        var pointer = handle.IsPointerTypedef ? handle.NativeName : handle.NativeName + "*";
        WriteTypeDocs(writer, handle.NativeName, handle.Documentation,
            $"A handle wrapping a native `{pointer}`. It owns nothing: copies share the native object, and nothing releases it implicitly.");
        WritePlatformAttributes(writer, handle.SupportedPlatforms, handle.UnsupportedPlatforms);
        writer.Open($"public readonly unsafe partial struct {handle.Name} : IEquatable<{handle.Name}>");
        DocWriter.Single(writer, "summary", "Initializes a handle from a native pointer.");
        writer.Line($"/// <param name=\"handle\">The native <c>{pointer}</c>.</param>");
        writer.Open($"public {handle.Name}(nint handle)");
        writer.Line("Handle = handle;");
        writer.Close();
        writer.Line();
        DocWriter.Single(writer, "summary", $"Gets the native `{pointer}`.");
        writer.Line("public nint Handle { get; }");
        writer.Line();
        DocWriter.Single(writer, "summary", "Gets a value indicating whether the native pointer is null.");
        writer.Line("public bool IsNull => Handle == 0;");
        foreach (var (op, verb) in new[] { ("==", "point to the same native object"), ("!=", "point to different native objects") })
        {
            writer.Line();
            DocWriter.Single(writer, "summary", $"Returns whether two handles {verb}.");
            writer.Line("/// <param name=\"left\">The first handle.</param>");
            writer.Line("/// <param name=\"right\">The second handle.</param>");
            writer.Line($"/// <returns><see langword=\"true\"/> if the handles {verb}.</returns>");
            writer.Line($"public static bool operator {op}({handle.Name} left, {handle.Name} right) => left.Handle {op} right.Handle;");
        }

        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public bool Equals({handle.Name} other) => Handle == other.Handle;");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public override bool Equals(object? obj) => obj is {handle.Name} other && Equals(other);");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line("public override int GetHashCode() => Handle.GetHashCode();");

        foreach (var function in instanceFunctions)
        {
            var name = names[function];
            var rest = function.Parameters.Skip(1).ToList();
            writer.Line();
            WriteFunctionDocs(writer, function, rest, generic: false);
            WritePlatformAttributes(writer, function);
            var rawParameters = string.Join(", ", rest.Select(p => $"{TypeName(p.Type, shadowed)} {p.Name}"));
            var rawArguments = string.Join(string.Empty, rest.Select(p => ", " + p.Name));
            writer.Line($"public {TypeName(function.Return, shadowed)} {name}({rawParameters}) => {_model.FunctionsClass}.{function.Name}(this{rawArguments});");

            if (HasFriendlyForm(function))
            {
                var exposed = rest.Where(p => p.Kind != ParameterKind.Count).ToList();
                writer.Line();
                WriteFunctionDocs(writer, function, exposed, generic: true);
                WritePlatformAttributes(writer, function);
                var parameters = string.Join(", ", exposed.Select(p => $"{FriendlyType(function, p, shadowed)} {p.Name}"));
                var arguments = string.Join(string.Empty, exposed.Select(p => ", " + p.Kind switch
                {
                    ParameterKind.In => "in " + p.Name,
                    ParameterKind.Out => "out " + p.Name,
                    ParameterKind.Ref => "ref " + p.Name,
                    _ => p.Name,
                }));
                writer.Line($"public {TypeName(function.Return, shadowed)} {name}{TypeParameters(function)}({parameters}){Constraints(function)} => {_model.FunctionsClass}.{function.Name}(this{arguments});");
            }
        }

        writer.Close();
        return Finish(writer, nullable: true);
    }

    private void WriteFunctionDocs(CodeWriter writer, FunctionModel function, IReadOnlyList<ParameterModel> parameters, bool generic)
    {
        var documentation = function.Documentation;
        var binds = $"Binds `{function.NativeName}`.";
        var remarks = new List<DocBlock>();
        if (documentation.Summary is not null)
        {
            remarks.Add(new DocBlock(DocBlockKind.Paragraph, [binds]));
        }

        remarks.AddRange(documentation.Remarks);
        foreach (var parameter in parameters)
        {
            remarks.AddRange(CallbackDocs(parameter.NativeName, parameter.Type));
        }

        var parameterDocs = parameters
            .Select(p => KeyValuePair.Create(p.Name, documentation.Parameters.GetValueOrDefault(p.NativeName) ?? $"Native parameter `{p.NativeName}`."))
            .ToList();
        var returns = function.Return.Kind == TypeKind.Void ? null : documentation.Returns;
        DocWriter.Write(writer, documentation.Summary ?? binds, remarks, parameterDocs, returns);
        foreach (var parameter in generic ? parameters.Where(IsByteSpan) : [])
        {
            writer.Line($"/// <typeparam name=\"{TypeParameter(function, parameter)}\">{DocWriter.Inline($"The element type of `{parameter.Name.TrimStart('@')}`, passed as bytes.")}</typeparam>");
        }
    }

    private void WriteFieldDocs(CodeWriter writer, FieldModel field)
    {
        var summary = field.Documentation.Summary ?? $"Binds `{field.NativeName}`.";
        var callback = CallbackDocs(field.NativeName, field.Type);
        if (callback.Count == 0)
        {
            DocWriter.Single(writer, "summary", summary);
        }
        else
        {
            DocWriter.Write(writer, summary, callback, [], null);
        }
    }

    // A callback typedef's own documentation, carried to each parameter or field that uses it: C# has no named function
    // pointer types to hang it on.
    private List<DocBlock> CallbackDocs(string name, TypeRef type)
    {
        var blocks = new List<DocBlock>();
        if (type is not { Kind: TypeKind.FunctionPointer, Alias: { } alias } || !_model.Callbacks.TryGetValue(alias, out var documentation))
        {
            return blocks;
        }

        blocks.Add(new DocBlock(DocBlockKind.Paragraph, [$"`{name}` is a `{alias}`: {documentation.Summary ?? "a callback."}"]));
        var items = documentation.Parameters.Select(p => $"`{p.Key}`: {p.Value}").ToList();
        if (documentation.Returns is { } returns)
        {
            items.Add($"Returns {returns}");
        }

        if (items.Count > 0)
        {
            blocks.Add(new DocBlock(DocBlockKind.List, items));
        }

        return blocks;
    }

    private static void WriteTypeDocs(CodeWriter writer, string nativeName, Documentation documentation, string? note = null)
    {
        var binds = $"Binds `{nativeName}`.";
        var remarks = new List<DocBlock>();
        if (documentation.Summary is not null)
        {
            remarks.Add(new DocBlock(DocBlockKind.Paragraph, [binds]));
        }

        if (note is not null)
        {
            remarks.Add(new DocBlock(DocBlockKind.Paragraph, [note]));
        }

        remarks.AddRange(documentation.Remarks);
        DocWriter.Write(writer, documentation.Summary ?? binds, remarks, [], null);
    }

    private void WritePlatformAttributes(CodeWriter writer, FunctionModel function) => WritePlatformAttributes(writer, function.SupportedPlatforms, function.UnsupportedPlatforms);

    private void WritePlatformAttributes(CodeWriter writer, IReadOnlyList<string> supported, IReadOnlyList<string> unsupported)
    {
        foreach (var (attribute, platform) in supported.Select(p => ("SupportedOSPlatform", p)).Concat(unsupported.Select(p => ("UnsupportedOSPlatform", p))))
        {
            _usings.Add("System.Runtime.Versioning");
            writer.Line($"[{attribute}(\"{platform}\")]");
        }
    }

    private static bool HasFriendlyForm(FunctionModel function) => function.Parameters.Any(p => p.Kind != ParameterKind.None);

    private static string InlineArrayName(FieldModel field) => field.Name + "Array";

    private string FriendlyType(FunctionModel function, ParameterModel parameter, HashSet<string> shadowed) => parameter.Kind switch
    {
        ParameterKind.Utf8String or ParameterKind.StringView => "ReadOnlySpan<byte>",
        ParameterKind.In => "in " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Out => "out " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Ref => "ref " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Span => $"{(parameter.Type.IsConst ? "ReadOnlySpan" : "Span")}<{(IsByteSpan(parameter) ? TypeParameter(function, parameter) : TypeName(parameter.Type.Element!, shadowed))}>",
        _ => TypeName(parameter.Type, shadowed),
    };

    // A `void*` and byte count pair takes a span of any unmanaged type, so callers pass their own element type without
    // converting to bytes first.
    private static bool IsByteSpan(ParameterModel parameter) => parameter.Kind == ParameterKind.Span && parameter.Type.Element!.Kind == TypeKind.Void;

    private static string TypeParameter(FunctionModel function, ParameterModel parameter) =>
        function.Parameters.Count(IsByteSpan) == 1 ? "T" : "T" + char.ToUpperInvariant(parameter.Name.TrimStart('@')[0]) + parameter.Name.TrimStart('@')[1..];

    private static string TypeParameters(FunctionModel function)
    {
        var names = function.Parameters.Where(IsByteSpan).Select(p => TypeParameter(function, p)).ToList();
        return names.Count == 0 ? string.Empty : $"<{string.Join(", ", names)}>";
    }

    private static string Constraints(FunctionModel function) =>
        string.Concat(function.Parameters.Where(IsByteSpan).Select(p => $" where {TypeParameter(function, p)} : unmanaged"));

    private string CountArgument(FunctionModel function, ParameterModel count, HashSet<string> shadowed)
    {
        var span = function.Parameters.First(p => p.Name == count.Pair);
        if (IsByteSpan(span))
        {
            // A span cannot exceed the address space, so the product fits nuint.
            var bytes = $"(nuint){span.Name}.Length * (nuint)sizeof({TypeParameter(function, span)})";
            return count.Type.Is(PrimitiveType.NUInt) ? bytes : $"({TypeName(count.Type, shadowed)})({bytes})";
        }

        return count.Type.Is(PrimitiveType.Int32) ? $"{span.Name}.Length" : $"({TypeName(count.Type, shadowed)}){span.Name}.Length";
    }

    private string StringViewArgument(ParameterModel parameter, HashSet<string> shadowed)
    {
        var view = _model.StringView ?? throw new InvalidOperationException($"{_model.Name}: {parameter.NativeName} is a string view, but the model names no string view struct.");
        var structModel = _structs[view.Struct];
        var data = structModel.Fields.First(f => f.NativeName == view.Data);
        var length = structModel.Fields.First(f => f.NativeName == view.Length);
        return $"new {TypeName(TypeRef.Named(view.Struct), shadowed)} {{ {data.Name} = {PinnedLocal(parameter)}, {length.Name} = ({TypeName(length.Type, shadowed)}){parameter.Name}.Length }}";
    }

    private static bool HasFunctionPointer(FunctionModel function) =>
        function.Return.Kind == TypeKind.FunctionPointer || function.Parameters.Any(p => p.Type.Kind == TypeKind.FunctionPointer);

    private static string ImportName(FunctionModel function) => HasFunctionPointer(function) ? function.Name + "Import" : function.Name;

    private string ImportTypeName(TypeRef type, HashSet<string> shadowed) => type.Kind == TypeKind.FunctionPointer ? "nint" : TypeName(type, shadowed);

    private string TypeName(TypeRef type, HashSet<string> shadowed) => type.Kind switch
    {
        TypeKind.Void => "void",
        TypeKind.Primitive => Keyword(type.Primitive),
        TypeKind.Pointer => TypeName(type.Element!, shadowed) + "*",
        TypeKind.Named => Qualify(_managedNames[type.Name!], shadowed),
        TypeKind.FunctionPointer => $"delegate* unmanaged[Cdecl]<{string.Join(", ", type.Parameters.Append(type.Return!).Select(t => TypeName(t, shadowed)))}>",
        _ => throw new InvalidOperationException($"{type.Kind} has no C# type name outside a field."),
    };

    // A member with the same name as a type hides the type inside the declaring type's body.
    private string Qualify(string name, HashSet<string> shadowed) => shadowed.Contains(name) ? $"global::{_model.Namespace}.{name}" : name;

    private string Keyword(PrimitiveType primitive)
    {
        if (primitive is PrimitiveType.CLong or PrimitiveType.CULong)
        {
            _usings.Add("System.Runtime.InteropServices");
        }

        return primitive switch
        {
            PrimitiveType.Bool => "bool",
            PrimitiveType.Char or PrimitiveType.Byte => "byte",
            PrimitiveType.SByte => "sbyte",
            PrimitiveType.Int16 => "short",
            PrimitiveType.UInt16 => "ushort",
            PrimitiveType.Int32 => "int",
            PrimitiveType.UInt32 => "uint",
            PrimitiveType.Int64 => "long",
            PrimitiveType.UInt64 => "ulong",
            PrimitiveType.NInt => "nint",
            PrimitiveType.NUInt => "nuint",
            PrimitiveType.CLong => "CLong",
            PrimitiveType.CULong => "CULong",
            PrimitiveType.Single => "float",
            PrimitiveType.Double => "double",
            _ => throw new ArgumentOutOfRangeException(nameof(primitive), primitive, null),
        };
    }

    private static string EnumValue(EnumModel enumModel, ulong bits) => FormatInteger(enumModel.Underlying, bits, hex: enumModel.IsFlags);

    // Unsigned constants are usually masks or sentinels, which read best in hexadecimal.
    private static string IntegerLiteral(PrimitiveType primitive, ulong bits, string nativeName)
    {
        var text = FormatInteger(primitive, bits, hex: primitive is PrimitiveType.Byte or PrimitiveType.UInt16 or PrimitiveType.UInt32 or PrimitiveType.UInt64 or PrimitiveType.NUInt);
        var fits = primitive switch
        {
            PrimitiveType.NInt => (long)bits is >= int.MinValue and <= int.MaxValue,
            PrimitiveType.NUInt => bits <= uint.MaxValue,
            _ => true,
        };
        return fits ? text : throw new InvalidOperationException($"{nativeName}: a native-sized constant must fit 32 bits; exclude it or map it.");
    }

    private static string FormatInteger(PrimitiveType primitive, ulong bits, bool hex)
    {
        var size = primitive is PrimitiveType.NInt or PrimitiveType.NUInt ? 4 : LayoutCalculator.SizeOf(primitive, 8, 8);
        var signed = primitive is PrimitiveType.SByte or PrimitiveType.Int16 or PrimitiveType.Int32 or PrimitiveType.Int64 or PrimitiveType.NInt;
        if (signed)
        {
            var shift = 64 - (size * 8);
            return ((long)(bits << shift) >> shift).ToString(CultureInfo.InvariantCulture);
        }

        var masked = size == 8 ? bits : bits & ((1UL << (size * 8)) - 1);
        return hex ? "0x" + masked.ToString("X" + (size * 2).ToString(CultureInfo.InvariantCulture), CultureInfo.InvariantCulture) : masked.ToString(CultureInfo.InvariantCulture);
    }

    private static string FloatLiteral(double value, string suffix)
    {
        var type = suffix == "F" ? "float" : "double";
        if (double.IsNaN(value))
        {
            return type + ".NaN";
        }

        if (double.IsInfinity(value))
        {
            return value > 0 ? type + ".PositiveInfinity" : type + ".NegativeInfinity";
        }

        var text = suffix == "F" ? ((float)value).ToString("R", CultureInfo.InvariantCulture) : value.ToString("R", CultureInfo.InvariantCulture);
        return text + suffix;
    }

    private static string StringLiteral(string text)
    {
        var builder = new StringBuilder("\"");
        foreach (var c in text)
        {
            if (c is '"' or '\\')
            {
                builder.Append('\\').Append(c);
            }
            else if (c < ' ')
            {
                builder.Append("\\u").Append(((int)c).ToString("X4", CultureInfo.InvariantCulture));
            }
            else
            {
                builder.Append(c);
            }
        }

        return builder.Append('"').ToString();
    }

    private static string PinnedLocal(ParameterModel parameter) => parameter.Name.TrimStart('@') + "Ptr";

    private static string Utf8Local(ParameterModel parameter) => parameter.Name.TrimStart('@') + "Utf8";

    // Locals are named after their parameter plus a suffix, so a parameter already spelled that way would clash.
    private static void CheckLocals(FunctionModel function)
    {
        var parameters = function.Parameters.Select(p => p.Name.TrimStart('@')).ToHashSet(StringComparer.Ordinal);
        var locals = function.Parameters
            .Where(p => p.Kind is not (ParameterKind.None or ParameterKind.Count))
            .SelectMany(p => p.Kind == ParameterKind.Utf8String ? new[] { PinnedLocal(p), Utf8Local(p) } : [PinnedLocal(p)]);
        if (locals.FirstOrDefault(parameters.Contains) is { } clash)
        {
            throw new InvalidOperationException($"{function.NativeName}: the generated local {clash} clashes with a parameter; rename the parameter in the config.");
        }
    }

    private string Finish(CodeWriter body, bool nullable = false)
    {
        var writer = new CodeWriter();
        writer.Line(Header);
        writer.Line();
        if (nullable)
        {
            writer.Line("#nullable enable");
            writer.Line();
        }

        foreach (var name in _usings)
        {
            writer.Line($"using {name};");
        }

        if (_usings.Count > 0)
        {
            writer.Line();
        }

        _usings.Clear();
        writer.Line($"namespace {_model.Namespace};");
        writer.Line();
        return writer + body.ToString();
    }
}
