using System.Globalization;

/// <summary>
/// Turns a <see cref="LibraryModel"/> into C# files following ADR-0006: a raw 1:1 import per function, friendly
/// overloads where parameters are annotated, enums, structs and handles with instance methods. The output only
/// depends on the model, so it is byte-identical for identical inputs.
/// </summary>
internal sealed class CSharpEmitter
{
    /// <summary>The first line of every generated file.</summary>
    public const string Header = "// <auto-generated/> by scripts/generate-bindings.cs. Do not edit: change the generator or its config and regenerate.";

    private readonly LibraryModel _model;
    private readonly ImportStyle _importStyle;
    private readonly Dictionary<string, string> _managedNames = new(StringComparer.Ordinal);
    private readonly SortedSet<string> _usings = new(StringComparer.Ordinal);

    /// <summary>Creates an emitter.</summary>
    /// <param name="model">The library to emit.</param>
    /// <param name="importStyle">How raw functions are imported.</param>
    public CSharpEmitter(LibraryModel model, ImportStyle importStyle)
    {
        _model = model;
        _importStyle = importStyle;
        foreach (var (native, managed) in model.Enums.Select(e => (e.NativeName, e.Name))
            .Concat(model.Structs.Select(s => (s.NativeName, s.Name)))
            .Concat(model.Handles.Select(h => (h.NativeName, h.Name))))
        {
            _managedNames.Add(native, managed);
        }
    }

    /// <summary>Renders every file of the library.</summary>
    /// <returns>File contents by file name, in ordinal order.</returns>
    /// <exception cref="InvalidOperationException">Two declarations map to the same C# name.</exception>
    public IReadOnlyDictionary<string, string> Emit()
    {
        var files = new SortedDictionary<string, string>(StringComparer.Ordinal);
        void Add(string name, string content)
        {
            if (!files.TryAdd(name, content))
            {
                throw new InvalidOperationException($"{_model.Name}: two declarations produce {name}; rename one in the config.");
            }
        }

        for (var i = 0; i < _model.Groups.Count; i++)
        {
            var (group, source) = _model.Groups[i];
            var functions = _model.Functions.Where(f => f.Group == group).ToList();
            Add($"{_model.FunctionsClass}.{group}.g.cs", EmitGroup(source, functions, documentClass: i == 0));
        }

        foreach (var enumModel in _model.Enums)
        {
            Add($"{enumModel.Name}.g.cs", EmitEnum(enumModel));
        }

        foreach (var structModel in _model.Structs)
        {
            Add($"{structModel.Name}.g.cs", EmitStruct(structModel));
        }

        foreach (var handle in _model.Handles)
        {
            Add($"{handle.Name}.g.cs", EmitHandle(handle));
        }

        return files;
    }

    /// <summary>Returns the name of a handle's instance method for a function taking the handle first.</summary>
    /// <param name="function">The function's C# name, for example <c>GetWindowSize</c>.</param>
    /// <param name="handle">The handle's C# name, for example <c>Window</c>.</param>
    /// <returns>The name without the handle right after its leading verb (<c>GetSize</c>), or unchanged.</returns>
    public static string InstanceName(string function, string handle)
    {
        static bool Boundary(string name, int index) => index == name.Length || !char.IsLower(name[index]);

        if (function.StartsWith(handle, StringComparison.Ordinal) && Boundary(function, handle.Length) && function.Length > handle.Length)
        {
            return function[handle.Length..];
        }

        var verb = 1;
        while (verb < function.Length && !char.IsUpper(function[verb]))
        {
            verb++;
        }

        return function.AsSpan(verb).StartsWith(handle, StringComparison.Ordinal) && Boundary(function, verb + handle.Length)
            ? function[..verb] + function[(verb + handle.Length)..]
            : function;
    }

    private string EmitGroup(string source, IReadOnlyList<FunctionModel> functions, bool documentClass)
    {
        var writer = new CodeWriter();
        var shadowed = _model.Functions.Select(f => f.Name).ToHashSet(StringComparer.Ordinal);
        if (documentClass)
        {
            DocWriter.Single(writer, "summary", $"Functions of {_model.Name}, imported from `jade_native`.");
        }

        writer.Open($"public static unsafe partial class {_model.FunctionsClass}");
        writer.Line($"// Functions from {source}.");
        foreach (var function in functions)
        {
            writer.Line();
            EmitRawFunction(writer, function, shadowed);
            if (HasFriendlyForm(function))
            {
                writer.Line();
                EmitFriendlyFunction(writer, function, shadowed);
            }
        }

        writer.Close();
        return Finish(writer);
    }

    private void EmitRawFunction(CodeWriter writer, FunctionModel function, HashSet<string> shadowed)
    {
        WriteFunctionDocs(writer, function, function.Parameters);
        var returnType = TypeName(function.Return, shadowed);
        var parameters = string.Join(", ", function.Parameters.Select(p => $"{TypeName(p.Type, shadowed)} {p.Name}"));
        _usings.Add("System.Runtime.InteropServices");
        if (_importStyle == ImportStyle.DllImport)
        {
            writer.Line($"[DllImport(\"jade_native\", EntryPoint = \"{function.NativeName}\", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]");
            WritePlatformAttributes(writer, function);
            writer.Line($"public static extern {returnType} {function.Name}({parameters});");
        }
        else
        {
            _usings.Add("System.Runtime.CompilerServices");
            writer.Line($"[LibraryImport(\"jade_native\", EntryPoint = \"{function.NativeName}\")]");
            writer.Line("[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
            WritePlatformAttributes(writer, function);
            writer.Line($"public static partial {returnType} {function.Name}({parameters});");
        }
    }

    private void EmitFriendlyFunction(CodeWriter writer, FunctionModel function, HashSet<string> shadowed)
    {
        var exposed = function.Parameters.Where(p => p.Kind != ParameterKind.Count).ToList();
        WriteFunctionDocs(writer, function, exposed);
        WritePlatformAttributes(writer, function);
        var signature = string.Join(", ", exposed.Select(p => $"{FriendlyType(p, shadowed)} {p.Name}"));
        CheckLocals(function);
        writer.Open($"public static {TypeName(function.Return, shadowed)} {function.Name}({signature})");

        foreach (var parameter in function.Parameters.Where(p => p.Kind == ParameterKind.Out))
        {
            // Cleared first: the callee may leave the value unwritten, typically when it fails.
            writer.Line($"{parameter.Name} = default;");
        }

        foreach (var parameter in function.Parameters.Where(p => p.Kind == ParameterKind.Utf8String))
        {
            writer.Line($"using var {Utf8Local(parameter)} = new NulTerminatedUtf8({parameter.Name}, stackalloc byte[NulTerminatedUtf8.StackLength]);");
        }

        var fixedCount = 0;
        foreach (var parameter in function.Parameters)
        {
            var pointer = parameter.Kind is ParameterKind.None or ParameterKind.Count ? null : TypeName(parameter.Type, shadowed);
            var initializer = parameter.Kind switch
            {
                ParameterKind.Utf8String => Utf8Local(parameter),
                ParameterKind.In or ParameterKind.Out or ParameterKind.Ref => $"&{parameter.Name}",
                ParameterKind.Span => parameter.Name,
                _ => null,
            };
            if (pointer is not null && initializer is not null)
            {
                writer.Line($"fixed ({pointer} {PinnedLocal(parameter)} = {initializer})");
                fixedCount++;
            }
        }

        if (fixedCount > 0)
        {
            writer.Line("{");
            writer.Indent();
        }

        var arguments = function.Parameters.Select(p => p.Kind switch
        {
            ParameterKind.None => p.Name,
            ParameterKind.Count => p.Type.Is(PrimitiveType.Int32) ? $"{p.Pair}.Length" : $"({TypeName(p.Type, shadowed)}){p.Pair}.Length",
            _ => PinnedLocal(p),
        });
        var call = $"{function.Name}({string.Join(", ", arguments)});";
        writer.Line(function.Return.Kind == TypeKind.Void ? call : "return " + call);

        if (fixedCount > 0)
        {
            writer.Unindent();
            writer.Line("}");
        }

        writer.Close();
    }

    private string EmitEnum(EnumModel enumModel)
    {
        var writer = new CodeWriter();
        WriteTypeDocs(writer, enumModel.NativeName, enumModel.Documentation);
        if (enumModel.IsFlags)
        {
            writer.Line("[Flags]");
        }

        writer.Open($"public enum {enumModel.Name} : {Keyword(enumModel.Underlying)}");
        var first = true;
        foreach (var member in enumModel.Members)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            DocWriter.Single(writer, "summary", member.Documentation.Summary ?? $"Binds `{member.NativeName}`.");
            writer.Line($"{member.Name} = {EnumValue(enumModel, member.Value)},");
        }

        writer.Close();
        return Finish(writer);
    }

    private string EmitStruct(StructModel structModel)
    {
        var writer = new CodeWriter();
        if (structModel.IsOpaque)
        {
            WriteTypeDocs(writer, structModel.NativeName, structModel.Documentation, "An opaque native type, only used through pointers.");
            writer.Open($"public partial struct {structModel.Name}");
            writer.Close();
            return Finish(writer);
        }

        _usings.Add("System.Runtime.InteropServices");
        WriteTypeDocs(writer, structModel.NativeName, structModel.Documentation);
        writer.Line(structModel.IsUnion ? "[StructLayout(LayoutKind.Explicit)]" : "[StructLayout(LayoutKind.Sequential)]");
        writer.Open($"public unsafe partial struct {structModel.Name}");
        var shadowed = structModel.Fields.Select(f => f.Name).ToHashSet(StringComparer.Ordinal);
        var first = true;
        foreach (var field in structModel.Fields)
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            DocWriter.Single(writer, "summary", field.Documentation.Summary ?? $"Binds `{field.NativeName}`.");
            if (structModel.IsUnion)
            {
                writer.Line("[FieldOffset(0)]");
            }

            writer.Line(field.Type.Kind == TypeKind.FixedArray
                ? $"public fixed {TypeName(field.Type.Element!, shadowed)} {field.Name}[{field.Type.Length}];"
                : $"public {TypeName(field.Type, shadowed)} {field.Name};");
        }

        writer.Close();
        return Finish(writer);
    }

    private string EmitHandle(HandleModel handle)
    {
        var writer = new CodeWriter();
        var instanceFunctions = _model.Functions
            .Where(f => f.Parameters.Count > 0 && f.Parameters[0].Kind == ParameterKind.None && f.Parameters[0].Type is { Kind: TypeKind.Named } first && first.Name == handle.NativeName)
            .ToList();
        var shadowed = instanceFunctions.Select(f => InstanceName(f.Name, handle.Name)).Concat(["Handle", "IsNull"]).ToHashSet(StringComparer.Ordinal);

        WriteTypeDocs(writer, handle.NativeName, handle.Documentation,
            $"A handle wrapping a native `{handle.NativeName}*`. It owns nothing: copies share the native object, and nothing releases it implicitly.");
        writer.Open($"public readonly unsafe partial struct {handle.Name} : IEquatable<{handle.Name}>");
        DocWriter.Single(writer, "summary", "Initializes a handle from a native pointer.");
        writer.Line($"/// <param name=\"handle\">The native <c>{handle.NativeName}*</c>.</param>");
        writer.Open($"public {handle.Name}(nint handle)");
        writer.Line("Handle = handle;");
        writer.Close();
        writer.Line();
        DocWriter.Single(writer, "summary", $"Gets the native `{handle.NativeName}*`.");
        writer.Line("public nint Handle { get; }");
        writer.Line();
        DocWriter.Single(writer, "summary", "Gets a value indicating whether the native pointer is null.");
        writer.Line("public bool IsNull => Handle == 0;");
        foreach (var (op, verb) in new[] { ("==", "point to the same native object"), ("!=", "point to different native objects") })
        {
            writer.Line();
            DocWriter.Single(writer, "summary", $"Returns whether two handles {verb}.");
            writer.Line("/// <param name=\"left\">The first handle.</param>");
            writer.Line("/// <param name=\"right\">The second handle.</param>");
            writer.Line($"/// <returns><see langword=\"true\"/> if the handles {verb}.</returns>");
            writer.Line($"public static bool operator {op}({handle.Name} left, {handle.Name} right) => left.Handle {op} right.Handle;");
        }
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public bool Equals({handle.Name} other) => Handle == other.Handle;");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line($"public override bool Equals(object? obj) => obj is {handle.Name} other && Equals(other);");
        writer.Line();
        writer.Line("/// <inheritdoc/>");
        writer.Line("public override int GetHashCode() => Handle.GetHashCode();");

        foreach (var function in instanceFunctions)
        {
            var name = InstanceName(function.Name, handle.Name);
            var rest = function.Parameters.Skip(1).ToList();
            writer.Line();
            WriteFunctionDocs(writer, function, rest);
            WritePlatformAttributes(writer, function);
            var rawParameters = string.Join(", ", rest.Select(p => $"{TypeName(p.Type, shadowed)} {p.Name}"));
            var rawArguments = string.Join(string.Empty, rest.Select(p => ", " + p.Name));
            writer.Line($"public {TypeName(function.Return, shadowed)} {name}({rawParameters}) => {_model.FunctionsClass}.{function.Name}(this{rawArguments});");

            if (HasFriendlyForm(function))
            {
                var exposed = rest.Where(p => p.Kind != ParameterKind.Count).ToList();
                writer.Line();
                WriteFunctionDocs(writer, function, exposed);
                WritePlatformAttributes(writer, function);
                var parameters = string.Join(", ", exposed.Select(p => $"{FriendlyType(p, shadowed)} {p.Name}"));
                var arguments = string.Join(string.Empty, exposed.Select(p => ", " + p.Kind switch
                {
                    ParameterKind.In => "in " + p.Name,
                    ParameterKind.Out => "out " + p.Name,
                    ParameterKind.Ref => "ref " + p.Name,
                    _ => p.Name,
                }));
                writer.Line($"public {TypeName(function.Return, shadowed)} {name}({parameters}) => {_model.FunctionsClass}.{function.Name}(this{arguments});");
            }
        }

        writer.Close();
        return Finish(writer, nullable: true);
    }

    private static void WriteFunctionDocs(CodeWriter writer, FunctionModel function, IReadOnlyList<ParameterModel> parameters)
    {
        var documentation = function.Documentation;
        var binds = $"Binds `{function.NativeName}`.";
        var remarks = documentation.Summary is null ? documentation.Remarks : [new DocBlock(DocBlockKind.Paragraph, [binds]), .. documentation.Remarks];
        var parameterDocs = parameters
            .Select(p => KeyValuePair.Create(p.Name, documentation.Parameters.GetValueOrDefault(p.NativeName) ?? $"Native parameter `{p.NativeName}`."))
            .ToList();
        var returns = function.Return.Kind == TypeKind.Void ? null : documentation.Returns;
        DocWriter.Write(writer, documentation.Summary ?? binds, remarks, parameterDocs, returns);
    }

    private static void WriteTypeDocs(CodeWriter writer, string nativeName, Documentation documentation, string? note = null)
    {
        var binds = $"Binds `{nativeName}`.";
        var remarks = new List<DocBlock>();
        if (documentation.Summary is not null)
        {
            remarks.Add(new DocBlock(DocBlockKind.Paragraph, [binds]));
        }

        if (note is not null)
        {
            remarks.Add(new DocBlock(DocBlockKind.Paragraph, [note]));
        }

        remarks.AddRange(documentation.Remarks);
        DocWriter.Write(writer, documentation.Summary ?? binds, remarks, [], null);
    }

    private void WritePlatformAttributes(CodeWriter writer, FunctionModel function)
    {
        foreach (var platform in function.UnsupportedPlatforms)
        {
            _usings.Add("System.Runtime.Versioning");
            writer.Line($"[UnsupportedOSPlatform(\"{platform}\")]");
        }
    }

    private static bool HasFriendlyForm(FunctionModel function) => function.Parameters.Any(p => p.Kind != ParameterKind.None);

    private string FriendlyType(ParameterModel parameter, HashSet<string> shadowed) => parameter.Kind switch
    {
        ParameterKind.Utf8String => "ReadOnlySpan<byte>",
        ParameterKind.In => "in " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Out => "out " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Ref => "ref " + TypeName(parameter.Type.Element!, shadowed),
        ParameterKind.Span => $"{(parameter.Type.IsConst ? "ReadOnlySpan" : "Span")}<{TypeName(parameter.Type.Element!, shadowed)}>",
        _ => TypeName(parameter.Type, shadowed),
    };

    private string TypeName(TypeRef type, HashSet<string> shadowed) => type.Kind switch
    {
        TypeKind.Void => "void",
        TypeKind.Primitive => Keyword(type.Primitive),
        TypeKind.Pointer => TypeName(type.Element!, shadowed) + "*",
        TypeKind.Named => Qualify(_managedNames[type.Name!], shadowed),
        TypeKind.FunctionPointer => $"delegate* unmanaged[Cdecl]<{string.Join(", ", type.Parameters.Append(type.Return!).Select(t => TypeName(t, shadowed)))}>",
        _ => throw new InvalidOperationException($"{type.Kind} has no C# type name outside a field."),
    };

    // A member with the same name as a type hides the type inside the declaring type's body.
    private string Qualify(string name, HashSet<string> shadowed) => shadowed.Contains(name) ? $"global::{_model.Namespace}.{name}" : name;

    private string Keyword(PrimitiveType primitive)
    {
        if (primitive is PrimitiveType.CLong or PrimitiveType.CULong)
        {
            _usings.Add("System.Runtime.InteropServices");
        }

        return primitive switch
        {
            PrimitiveType.Char or PrimitiveType.Byte => "byte",
            PrimitiveType.SByte => "sbyte",
            PrimitiveType.Int16 => "short",
            PrimitiveType.UInt16 => "ushort",
            PrimitiveType.Int32 => "int",
            PrimitiveType.UInt32 => "uint",
            PrimitiveType.Int64 => "long",
            PrimitiveType.UInt64 => "ulong",
            PrimitiveType.NInt => "nint",
            PrimitiveType.NUInt => "nuint",
            PrimitiveType.CLong => "CLong",
            PrimitiveType.CULong => "CULong",
            PrimitiveType.Single => "float",
            PrimitiveType.Double => "double",
            _ => throw new ArgumentOutOfRangeException(nameof(primitive), primitive, null),
        };
    }

    private static string EnumValue(EnumModel enumModel, ulong bits)
    {
        var size = LayoutCalculator.SizeOf(enumModel.Underlying, 8, 8);
        var signed = enumModel.Underlying is PrimitiveType.SByte or PrimitiveType.Int16 or PrimitiveType.Int32 or PrimitiveType.Int64;
        if (signed)
        {
            var shift = 64 - (size * 8);
            return ((long)(bits << shift) >> shift).ToString(CultureInfo.InvariantCulture);
        }

        var masked = size == 8 ? bits : bits & ((1UL << (size * 8)) - 1);
        return enumModel.IsFlags ? "0x" + masked.ToString("X" + (size * 2).ToString(CultureInfo.InvariantCulture), CultureInfo.InvariantCulture) : masked.ToString(CultureInfo.InvariantCulture);
    }

    private static string PinnedLocal(ParameterModel parameter) => parameter.Name.TrimStart('@') + "Ptr";

    private static string Utf8Local(ParameterModel parameter) => parameter.Name.TrimStart('@') + "Utf8";

    // Locals are named after their parameter plus a suffix, so a parameter already spelled that way would clash.
    private static void CheckLocals(FunctionModel function)
    {
        var parameters = function.Parameters.Select(p => p.Name.TrimStart('@')).ToHashSet(StringComparer.Ordinal);
        var locals = function.Parameters
            .Where(p => p.Kind is not (ParameterKind.None or ParameterKind.Count))
            .SelectMany(p => p.Kind == ParameterKind.Utf8String ? new[] { PinnedLocal(p), Utf8Local(p) } : [PinnedLocal(p)]);
        if (locals.FirstOrDefault(parameters.Contains) is { } clash)
        {
            throw new InvalidOperationException($"{function.NativeName}: the generated local {clash} clashes with a parameter; rename the parameter in the config.");
        }
    }

    private string Finish(CodeWriter body, bool nullable = false)
    {
        var writer = new CodeWriter();
        writer.Line(Header);
        writer.Line();
        if (nullable)
        {
            writer.Line("#nullable enable");
            writer.Line();
        }

        foreach (var name in _usings)
        {
            writer.Line($"using {name};");
        }

        if (_usings.Count > 0)
        {
            writer.Line();
        }

        _usings.Clear();
        writer.Line($"namespace {_model.Namespace};");
        writer.Line();
        return writer + body.ToString();
    }
}
